### ISSUE TITLE
How can I decorate the scroll bar?

### ISSUE THREAD

**Issue by UltimateYZ** [JFormDesigner/FlatLaf#103]
Hi JFormDesigner,

I wanted to know how can I decorate the scroll bar.

**Comment by DevCharly** [comment]
Don't know what you mean.
Can you provide more details?

If you want arrow buttons or wider scroll bars, see:
https://www.formdev.com/flatlaf/customizing/#scrollbar

**Comment by UltimateYZ** [comment]
I mean changing the shape and decorate the scroll bar like this:

![Screenshot from 2020-05-19 18-24-09](https://user-images.githubusercontent.com/55871338/82352236-fbe3b000-99fd-11ea-8763-e3965a6990e9.png)

That above is Ubuntu's scroll bar

**Comment by DevCharly** [comment]
You can subclass `FlatScrollBarUI` and implement own [painting methods](https://github.com/JFormDesigner/FlatLaf/blob/ddf9ed06ab20372d2519877a043ea7f25a28509e/flatlaf-core/src/main/java/com/formdev/flatlaf/ui/FlatScrollBarUI.java#L216-L229).

Here is a working example that paints round thumbs:
~~~java
public class MyFlatScrollBarUI
	extends FlatScrollBarUI
{
	public static ComponentUI createUI( JComponent c ) {
		return new MyFlatScrollBarUI();
	}

	@Override
	protected void paintThumb( Graphics g, JComponent c, Rectangle thumbBounds ) {
		if( thumbBounds.isEmpty() || !scrollbar.isEnabled() )
			return;

		FlatUIUtils.setRenderingHints( (Graphics2D) g );

		int arc = Math.min( c.getWidth(), c.getHeight() ) - 2;
		g.setColor( thumbColor );
		g.fillRoundRect( thumbBounds.x + 1, thumbBounds.y + 1, thumbBounds.width - 2, thumbBounds.height - 2, arc, arc );
	}
}
~~~

Unfortunately it is currently not possible to paint the thumb in a darker color when the mouse is over it because the hover field is private.  I'll change that for the next version.
The class must be public.

Then register the class in `main` after installing FlatLaf with:
~~~java
UIManager.put( "ScrollBarUI", "com.myproject.MyFlatScrollBarUI" );
~~~

This looks like:
![image](https://user-images.githubusercontent.com/5604048/82356146-7f53d000-9a03-11ea-9491-a380c0d9f675.png)


Anyway, I'm open to support different scrollbar styles out of the box.
Any suggestions are welcome 😉

**Comment by UltimateYZ** [comment]
Thanks, DevCharly.

**Comment by DevCharly** [comment]
Since FlatLaf 0.36 it is possible to use different styles for scroll bars.
See https://www.formdev.com/flatlaf/customizing/#scrollbar_style
