### ISSUE TITLE
Make inner classes protected...

### ISSUE THREAD

**Issue by mlaggner** [JFormDesigner/FlatLaf#113]
... to avoid copying the whole content of the inner class when creating subclasses

e.g. where I found an example https://github.com/JFormDesigner/FlatLaf/blob/master/flatlaf-core/src/main/java/com/formdev/flatlaf/ui/FlatTableHeaderUI.java#L255

**Comment by mlaggner** [comment]
another similar example would be private helper methods like FlatComboBoxUI.getDisabledBackground() which I had to re-implement in the subclass just to adopt the paint method a bit

**Comment by DevCharly** [comment]
I'm willing to open FlatLaf as much as possible, but I'm not sure whether opening `FlatTableCellHeaderRenderer` is a good idea. This class is not a general header renderer. It is only used  when sort icon position is not on right side. And it always delegates to the default header renderer.

What's your use case for subclassing `FlatTableCellHeaderRenderer` ?

**Comment by mlaggner** [comment]
the problem here was that I use glazedlists for my tables and glazedlists needs a component which implements the interface `SortableRenderer` as header renderer to inject the sort icon into the header. So my idea was to

```
private static class MyHeaderRenderer extends FlatTableCellHeaderRenderer  implements SortableRenderer {
...
}
```

to achieve this without the need to copy the whole inner class.

Creating sub-themes on your theme would be much easier if we could use as much code as possible (`protected`). Just my personal opinion

**Comment by DevCharly** [comment]
Implemented a little app to test Glazed Lists with FlatLaf (in commit 212c553904f75aae7e9b6928f252aab8f3fd24b7) and the table header sort icons work out of the box (without a custom header renderer and without `FlatTableCellHeaderRenderer` involved):

![image](https://user-images.githubusercontent.com/5604048/84790900-2ff8c380-aff2-11ea-9be7-53103521b61d.png)

Top/bottom/left positioned sort arrows did not work, but is fixed in 211030b5b6b0beac5a60b954ea89c9a681b77d94 (enable with `UIManager.put( "TableHeader.sortIconPosition", "top" );`. This commit also changes how class `FlatTableCellHeaderRenderer` is internally used. Default renderer of JTableHeader is no longer changed permanently. Only temporary while painting.

![image](https://user-images.githubusercontent.com/5604048/84804424-0bf1ae00-b003-11ea-9449-7910ab8db487.png)

Little "problem" is that this uses non-HiDPI icons from Glazed Lists. It is possible to replace them with `TableComparatorChooser.setIconPath( "path" )` (see https://github.com/JFormDesigner/FlatLaf/blob/212c553904f75aae7e9b6928f252aab8f3fd24b7/flatlaf-testing/src/main/java/com/formdev/flatlaf/testing/glazedlists/FlatGlazedListsTest.java#L70), but this supports only PNGs.

Is your plan/idea to use `SortableRenderer` to replace glazedlists icons with FlatLaf icons?

This is probably difficult because the only method of the interface is `void setSortIcon(Icon sortIcon)` and does not have any information about the column or sort direction.

Would be easy if Glazed Lists would provide a `TableComparatorChooser.setIcons(Icon[] icons)` method. As workaround you could use reflection to set field `TableComparatorChooser.icons`.


BTW the recommended way to implement custom header renderer, which works with all look and feels, is:
~~~java
private static class MyHeaderRenderer implements TableCellRenderer {
    private final TableCellRenderer delegate;

    MyHeaderRenderer( TableCellRenderer delegate ) {
        this.delegate = delegate;
    }

    @Override
    public Component getTableCellRendererComponent( JTable table, Object value, boolean isSelected, boolean hasFocus, int row, int column ) {
        Component c = delegate.getTableCellRendererComponent( table, value, isSelected, hasFocus, row, column );
        // TODO do some modifications
        return c;
    }
}

// install own header renderer
JTableHeader header = itemsTable.getTableHeader();
header.setDefaultRenderer( new MyHeaderRenderer( header.getDefaultRenderer() ) );
~~~

Still don't think that it is necessary to copy code from `FlatTableCellHeaderRenderer` or subclass it, but I'm open for arguments...

Regarding other private methods/fields/classes: I plan to review them soon and will make them protected where it may be useful...

**Comment by mlaggner** [comment]
wow, even more that I could imagine! thanks!

**Comment by mlaggner** [comment]
> Is your plan/idea to use SortableRenderer to replace glazedlists icons with FlatLaf icons?

yes this would be the next step. 

initially I created a header renderer which is able to display an icon instead of text AND the sort icon (so I need basically 2 JLabels). Something like 
![image](https://user-images.githubusercontent.com/1523778/84813654-8ecd3580-b010-11ea-8bcb-a729364562fc.png)

**Comment by DevCharly** [comment]
@mlaggner wrote:
> another similar example would be private helper methods like FlatComboBoxUI.getDisabledBackground() which I had to re-implement in the subclass just to adopt the paint method a bit

I've reviewed all private methods and made them protected/public where it might be useful for subclasses in commit ea2412d3a705900ff82fa748b0a46d38efb9de9c. Also made some changes to `FlatComboBoxUI` and `FlatSpinnerUI`, which now have protected `getBackground(boolean enabled)` and `getForeground(boolean enabled)` methods.

**Comment by mlaggner** [comment]
thanks, will review my "patches" as soon as 0.37 is released.  
And with your help about Glazedlists I was able to reimplement a TableComparatorChooser (mostly copied code, because I avoid using dirty reflection) with SVG sort icons

**Comment by nseven404** [comment]
![image](https://user-images.githubusercontent.com/59216545/89213196-ee969480-d5ee-11ea-9122-e9eb8d1038f1.png)
![image](https://user-images.githubusercontent.com/59216545/89213244-fd7d4700-d5ee-11ea-8215-e70ab73489d4.png)
Not working! :( Help me!

**Comment by DevCharly** [comment]
Did you enable table sorting? 
E.g. invoking `JTable.setAutoCreateRowSorter(true)`?
This is the code used in the FlatLaf Demo (on "Data components" tab; click on column header to sort column):
https://github.com/JFormDesigner/FlatLaf/blob/368fbcdeb0b66b0d40bb6773f928a8d31a02a006/flatlaf-demo/src/main/java/com/formdev/flatlaf/demo/DataComponentsPanel.java#L296

**Comment by nseven404** [comment]
Thanks you very much! I want to add an icon down on the header table bar, what should I do?

**Comment by DevCharly** [comment]
Here is a great article that gives many details about how to sort JTable:
https://www.codejava.net/java-se/swing/6-techniques-for-sorting-jtable-you-should-know
