### ISSUE TITLE
API to override L&F provided attributes (colors, insets, etc.)

### ISSUE THREAD

**Issue by Chrriis** [JFormDesigner/FlatLaf#117]
Hi,

I was experimenting having a menu bar with dark colors (just the menu bar, not its menus) and I realized that I cannot set all colors:
![CustomMenuBar](https://user-images.githubusercontent.com/1174202/85551063-e75c8e00-b621-11ea-9b6b-1d02e8d6d0ad.png)

I understand that the purpose of the look and feel is to define all colors for us. Still, is there a way to override colors for a given component? If not, would such API make sense?

Possible candidates off the top of my head:
- `menu.putClientProperty("FlatLaf.attribute.MenuItem.underlineSelectionBackground", Color.BLUE);`
- subclassing JMenu to provide this information somehow.
- changing the UI delegate (though this is a bit too much in my view).
- have the notion of a theme variant per component: e.g.: `menu.putClientProperty("FlatLaf.variant", "SpecialBar")`, which would load the properties from the look and feel named "SpecialBar.MenuItem.underlineSelectionBackground" with fallback to main variant for properties that are not defined.
- add "MenuBar.inverseColors" as a standard capability. It is what I wanted to achieve, but it is not uncommon these days for toolbars/menubars.

My test case:
[MenuBarWithStyle.zip](https://github.com/JFormDesigner/FlatLaf/files/4825177/MenuBarWithStyle.zip)

**Comment by DevCharly** [comment]
The menu hover colors are now fixed in latest commit.
They are derived at runtime from the background color.

To make the menu bar dark use:
~~~java
UIManager.put( "MenuBar.background", Color.DARK_GRAY );
UIManager.put( "MenuBar.foreground", Color.WHITE );
~~~
or
~~~java
menuBar.setBackground( Color.DARK_GRAY );
menuBar.setForeground( Color.WHITE );
~~~

Changing the foreground color of the top-level `JMenus` is not necessary. 
They now use the foreground of the `JMenuBar`.

**Comment by Chrriis** [comment]
Neat! 👍 

If I use the underline style for menus, is there a way to set the underline color of the menubar?

**Comment by DevCharly** [comment]
Menu underline color can be changed with (for all menu items):
~~~java
UIManager.put( "MenuItem.underlineSelectionColor", Color.RED );
~~~

If you want it only for the menu bar, there is a trick that works:
~~~java
UIManager.put( "MenuItem.underlineSelectionColor", Color.RED );

// create JMenus for menubar here
JMenu menu1 = new JMenu(title);

// restore to FlatLaf default color before creating menu items
UIManager.put( "MenuItem.underlineSelectionColor", null );
~~~

**Comment by DevCharly** [comment]
> I understand that the purpose of the look and feel is to define all colors for us. Still, is there a way to override colors for a given component? 

At the moment only standard Swing API (`setBackground()`, etc) and some client properties.

> If not, would such API make sense?

Sure, ideally it would be nice to change all UI values also for individual components, but that is not that easy to achieve. Those UI values are loaded from UIManager when creating components and stored in UI delegates (e.g. `FlatButtonUI`) or in icons (e.g. `FlatCheckBoxIcon`). Many of those classes are shared (only **one instance** for all components). Other UI delegates have one instance per component.

> Possible candidates off the top of my head:
> * `menu.putClientProperty("FlatLaf.attribute.MenuItem.underlineSelectionBackground", Color.BLUE);`

This kind is already used in some cases, but generally using client properties for all UI values in all UI delegates would be a nightmare to implement IMHO.

> * subclassing JMenu to provide this information somehow.

That is something that I consider to do in [flatlaf-extras](https://github.com/JFormDesigner/FlatLaf/tree/master/flatlaf-extras) sub-project for some cases.

> * changing the UI delegate (though this is a bit too much in my view).

Yep.

> * have the notion of a theme variant per component: e.g.: `menu.putClientProperty("FlatLaf.variant", "SpecialBar")`, which would load the properties from the look and feel named "SpecialBar.MenuItem.underlineSelectionBackground" with fallback to main variant for properties that are not defined.

Interesting, could work for non-shared UI delegates, but not for shared. Makes also problems for cases where the UI values are fetched in Java's `Basic*UI` classes, which FlatLaf extend.

Have recently implemented something similar for checkbox icons (in commit 84cc86bef772ccacd29bbc77a4350a4623ed9a2b) where it is possible to specify checkbox icon variants in properties files and choose one globally with e.g. `UIManager.put( "CheckBox.icon.style", "filled" );`, but this does not work for individual components because class `FlatCheckBoxIcon` is shared for all checkboxes.

https://github.com/JFormDesigner/FlatLaf/blob/84cc86bef772ccacd29bbc77a4350a4623ed9a2b/flatlaf-core/src/main/resources/com/formdev/flatlaf/FlatLightLaf.properties#L125-L137

Another possibility would be to have some kind of "UI configuration" classes that are used by UI delegates and can be set/modified via a single client property. E.g.
~~~java
class FlatButtonUIValues {
    // ...
    Color hoverBackground;
    Color pressedBackground;

    // getter/setter....
}
~~~

~~~java
FlatButtonUIValues uiValues = (FlatButtonUIValues) myButton.getClientProperty( "flatlaf.uiValues" );
if( uiValues == null ) {
    uiValues = new FlatButtonUIValues();
    myButton.putClientProperty( "flatlaf.uiValues", uiValues );
}
uiValues.setHoverBackground( Color.RED );
~~~

May I'll try something in the future. Currently I'd like to focus on fixing/polishing current code and release FlatLaf 1.0 as soon as possible...

**Comment by DevCharly** [comment]
Closing because this will be possible in v2 via styling.
See PRs #341 and #388.

For documentation of available properties see: https://www.formdev.com/flatlaf/components/
