### ISSUE TITLE
Internalframe and frame image/icon

### ISSUE THREAD

**Issue by Chrriis** [JFormDesigner/FlatLaf#122]
System L&F shows the Java icon for frames and internal frames that don't have one:
![InternalFrame2](https://user-images.githubusercontent.com/1174202/86446639-7fd6ca80-bd14-11ea-84d0-d05ca3f62316.png)

FlatLaf shows the Java icon for frames (whether or not the frame is decorated), but not for internal frames:
![InternalFrame1](https://user-images.githubusercontent.com/1174202/86446697-94b35e00-bd14-11ea-8bb3-0df85c0614c1.png)

I think the internal frame should have the same default icon than the frame.
If it cannot do that, it should have its own icon or the space reserved for the missing icon (matter of taste?).

One thing that would be great is to have a way to replace the default icon used by frames and internal frames (to replace the Java icon). I understand that for frames you need multiple images (image list) while for internal frames it is a single icon.

**Comment by DevCharly** [comment]
Thx, fixed in master branch.

The default icon (the duke) can be replaced by setting UI value `InternalFrame.icon` to any `javax.swing.Icon` implementation:

~~~java
UIManager.put( "InternalFrame.icon", new FlatFileViewFloppyDriveIcon() );
~~~

To use multiple bitmap images, you can use:

~~~java
List<Image> images = ...;
UIManager.put( "InternalFrame.icon", FlatTitlePaneIcon.create( images, new Dimension( 16, 16 ) ) );
~~~

**Comment by Chrriis** [comment]
Thanks, works as expected!
