### ISSUE TITLE
Shouldn't by default the pressed mouse event set a darker or brighter tone of the current custom color of thumb or hover, on scrollbar?

### ISSUE THREAD

**Issue by UltimateYZ** [JFormDesigner/FlatLaf#123]
Hello @JFormDesigner,

Well, I tested the new version of flatlaf, and I realized that it doesn't change the color of the scrollbar when pressed by left mice key, like it's supposed to.
I tried this:
`pressedThumbColor = thumbColor;
pressedThumbColor.darker();`

But still I'm not having any success...
I'm missing something?
And, is it normal to combo box text area grow big now every time it is supposed to receive a value?

**Comment by DevCharly** [comment]
A scrollbar consists of two parts: the track and the thumb. The track it the "background" and the thumb is the thing you can move around.

The thumb is automatically made darker in FlatLaf on mouse pressed. See:

![scrollbar](https://user-images.githubusercontent.com/5604048/86597645-4c0dd600-bf9c-11ea-874d-3f53eb9d04bb.gif)

The track on the other hand does not support "pressed" state. Only "hover".

You code seems to be wrong. Should be:
~~~java
pressedThumbColor = thumbColor.darker();
~~~

> And, is it normal to combo box text area grow big now every time it is supposed to receive a value?

No, but I'm not sure what you exactly mean.
Better create a new issue with more information (screenshots, test program).

**Comment by UltimateYZ** [comment]
Well, about the first issue it only occurs when I change the default color of hoverthumbcolor and thumbcolor. When I apply a new pressedthumbcolor, the whole scrollbar is painted with thumbcolor. Regardless when I hover it with mice, the color doesn't change. I've confirmed that with default color it doesn't occurs.

**Comment by DevCharly** [comment]
First of all please post code next time as text instead of a bitmap. I can copy text and try the code, but this is not possible with code bitmaps. Use following to get syntax highlighting:

    ~~~java
    // your Java code
    ~~~

To change thumb color either set UI values `ScrollBar.thumb`, `ScrollBar.hoverThumbColor`, `ScrollBar.pressedThumbColor` with e.g.
~~~java
UIManager.put( "ScrollBar.thumb", new Color(...) );
~~~
or override `FlatScrollBarUI.getThumbColor()` https://github.com/JFormDesigner/FlatLaf/blob/de6d45fee631378f941137e2d1516f4d78b0c411/flatlaf-core/src/main/java/com/formdev/flatlaf/ui/FlatScrollBarUI.java#L275

which gets a "pressed" flag as parameter.

Avoid changing protected fields of `FlatScrollBarUI` (if not really necessary).

The thumb insets can be applied with:
~~~java
UIManager.put( "ScrollBar.thumbInsets", new Insets(2,2,2,2) );
~~~
so that it actually is not necessary to override `paintThumb()`.

**Comment by UltimateYZ** [comment]
Thanks for the help.
