### ISSUE TITLE
Bug encountered on JComboBox. Text area too wide?!

### ISSUE THREAD

**Issue by UltimateYZ** [JFormDesigner/FlatLaf#124]
Hello @JFormDesigner,

I don't know if this only happens on Ubuntu... 
![Screenshot from 2020-07-06 18-54-42](https://user-images.githubusercontent.com/55871338/86619583-2cd27100-bfbb-11ea-904b-5f48956c70eb.png)
But I think that the text area is too big... On earlier versions it only showed, about 6-5 entries... Now... 
The first time I run a program, with the newest version of flatlaf, about days ago, It has scarred me! (Well the first entry has been replaced by an empty value, the same goes to the rest, after "Dezembro" - I was only "testing" it)

**Comment by DevCharly** [comment]
So there are real empty items after "Dezembro", right?

Then it should be OK. It looks weird because there are so many empty items at the end. Will look better with more text 😉 

In FlatLaf 0.37 I've changed the maximum row count for combobox lists from 8 to 20 items.
This makes the list taller, but avoids scrolling.

Maybe 20 rows was a bit too much... 
Will review...

You can change this with:
~~~java
UIManager.put( "ComboBox.maximumRowCount", 8 );
~~~

**Comment by UltimateYZ** [comment]
Oh! OK.
