### ISSUE TITLE
cannot find symbol   symbol:   variable FlatLightLaf   location: class xxx

### ISSUE THREAD

**Issue by t-m-z** [JFormDesigner/FlatLaf#13]
Whenn adding the line "FlatLightLaf.install();" to my java-classes, I receiv the error 
"cannot find symbol
  symbol:   variable FlatLightLaf
  location: class CarolaHartmannMilesVerlag"
although I addes the jar-file to my classpath.
I am using Netbeans 11.00.
What do I missing?
Kind regards
Thomas

**Comment by DevCharly** [comment]
Is this a compiler error?

Then this should help:
~~~java
import com.formdev.flatlaf.FlatLightLaf;
~~~

**Comment by t-m-z** [comment]
Unfortunately not. 

This message  is made by Netbeans.

 

When adding “import com.formdev.flatlaf.FlatLightLaf;” I receive the message
“cannot find symbol
  symbol:   class FlatLightLaf
  location: package com.formdev.flatlaf”

 

 

 

Von: Karl T <notifications@github.com> 
Gesendet: Freitag, 18. Oktober 2019 18:56
An: JFormDesigner/FlatLaf <FlatLaf@noreply.github.com>
Cc: Thomas <thomas@familiezimmermann.de>; Author <author@noreply.github.com>
Betreff: Re: [JFormDesigner/FlatLaf] cannot find symbol symbol: variable FlatLightLaf location: class xxx (#13)

 

Is this a compiler error?

Then this should help:

import com.formdev.flatlaf.FlatLightLaf;

**Comment by DevCharly** [comment]
Do you use Java 9 modules? Then you probably have to add following to your `module-info.java`:
~~~java
requires com.formdev.flatlaf;
~~~

**Comment by t-m-z** [comment]
No –  I do not use modules.

But I recognized that Netbeans compiles the code despite the message that the symbol could not be found and the FlatLightLaf-theme is used.

I am flabbergasted.

 

Regards

Thomas

 

Von: Karl T <notifications@github.com> 
Gesendet: Freitag, 18. Oktober 2019 19:26
An: JFormDesigner/FlatLaf <FlatLaf@noreply.github.com>
Cc: Thomas <thomas@familiezimmermann.de>; Author <author@noreply.github.com>
Betreff: Re: [JFormDesigner/FlatLaf] cannot find symbol symbol: variable FlatLightLaf location: class xxx (#13)

 

Do you use Java 9 modules? Then you probably have to add following to your module-info.java:

requires com.formdev.flatlaf;

**Comment by DevCharly** [comment]
Is the problem still there?

Did you try to rebuild project?
Or refresh Maven/Gradle?

**Comment by t-m-z** [comment]
Hello Karl,

 

the problem is still there.

I am using Netbeans 11.0 without Maven/Gradle.

The needed jar’s are in the classpath.

 

I am using the import “import com.formdev.flatlaf.FlatLightLaf;”  which shows the warning “cannot find symbol,   symbol:   class FlatLightLaf,   location: package com.formdev.flatlaf” and the code-snippet “FlatLightLaf.install();” to install the theme.

The whole project was successfully rebuild without any problems und the jar-file is running with the FlitLightLAF.

 

Regards

Thomas

 

Von: Karl T <notifications@github.com> 
Gesendet: Dienstag, 22. Oktober 2019 15:26
An: JFormDesigner/FlatLaf <FlatLaf@noreply.github.com>
Cc: Thomas <thomas@familiezimmermann.de>; Author <author@noreply.github.com>
Betreff: Re: [JFormDesigner/FlatLaf] cannot find symbol symbol: variable FlatLightLaf location: class xxx (#13)

 

Is the problem still there?

Did you try to rebuild project?
Or refresh Maven/Gradle?

**Comment by DevCharly** [comment]
This seems to be a bug in NetBeans.

@AlexFalappa describes the same issue here: http://mail-archives.apache.org/mod_mbox/netbeans-dev/201911.mbox/%3cCADBn96U94y=fBWnsny_R6tAD-m94YgiawcXQz66Z7SbD8pNfFw@mail.gmail.com%3e

It occurs because:
1. `flatlaf.jar` contains `.properties` files with same basename as `.class` files (e.g. `FlatLightLaf.properties` and `FlatLightLaf.class`)
2. and `flatlaf.jar` contains `META-INF/versions/9/module-info.class`
3. and `Multi-Release=true` is true in `flatlaf.jar`'s `MANIFEST.MF`
4. and NetBeans project uses JDK 9 or later source/binary format

@AlexFalappa the difference to `log4j-api-2.12.1.jar` are the  `.properties` files in FlatLaf.

When I remove `FlatLightLaf.properties` from `flatlaf.jar`, using class `FlatLightLaf` in NetBeans editor works. But I still can not use other classes that have corresponding `.properties` files (e.g. `FlatDarkLaf`). BTW the extension `.properties` is irrelevant. The problem occurs also with other extensions.

It also works when I remove `Multi-Release=true` from `MANIFEST.MF` and move `module-info.class` to the root of the JAR. In this case the `.properties` files do not confuse NetBeans.

Very strange...

**Comment by AlexFalappa** [comment]
@DevCharly thank you for the further investigation.

Would you mind answering to that thread in NetBeans dev mailinglist to help the developers troubleshoot the issue?

**Comment by mparusk** [comment]
Hi, I have the same issue - is there something I could do to use FlatLaf?

**Comment by DevCharly** [comment]
@mparusk Hi Maria, are you using a recent FlatLaf version? Because this issue is actually fixed since FlatLaf 0.20.

Did you add flatlaf.jar to the project modulepath (in Projects dialog)?
And flatlaf.jar is **not** shown in the Projects view under the Libraries node?
Then you have to create a `module-info.java` in your application and add FlatLaf as required module.
Use "New File > Java > Java Module Info" to create a module-info.java.
Then add `requires com.formdev.flatlaf;` to module-info.java. E.g.

~~~java
module MyApp {
    requires com.formdev.flatlaf;
}
~~~

**Comment by DevCharly** [comment]
closing because already fixed since FlatLaf 0.20

**Comment by r-go** [comment]
Just hit at it myself too:
NetBean 11.3
flatlaf-0.33.jar
macOS High Sierra 
Java 13

My project is Maven project and it does have flatlaf-0.33.jar dependency included. 
As you have explained, the properties files are masking .class files with the same name  
I did include module info  with  the requires com.formdev.flatlaf - but no difference 
Note: I see that the .properties files are still mixed up together with the .class files in the same jarr/package folder (i.e. they are not in resources folder as in the soruce code tree)
Regards

**Comment by DevCharly** [comment]
@r-go could you please test whether it works with FlatLaf 0.32?

**Comment by r-go** [comment]
Just did it and it works ! (and now all classes are visible to the code completion wizard too) . Thanks for the quick reply ! (and, btw - this is by far the best L&F ever released for Swing)

**Comment by neilcsmith-net** [comment]
@DevCharly just to confirm same issue with NetBeans 12.0-beta3 and Maven project (Ubuntu, Java 11).  Downgrading to 0.32 fixes it.  Do you know what the change that triggered it was?  Thanks!

**Comment by DevCharly** [comment]
@neilcsmith-net the reason is probably that flatlaf-0.33.jar is now again a multi-release JAR (MRJ). This was necessary to support Java 9+ multi-resolution images.

When this issue initially came up, flatlaf.jar was also a MRJ for `META-INF/versions/9/module-info.class`.
In 0.20 I moved `META-INF/versions/9/module-info.class` to `module-info.class` and removed MRJ to fix this issue.

**Comment by neilcsmith-net** [comment]
@DevCharly Thanks Karl.  Just noticed that when diffing the two JARs.  So same issue as before?  One for the NetBeans side of things then I guess.  Maybe that `module-info.class` could go back under `META-INF` as MRJ now anyway?

**Comment by neilcsmith-net** [comment]
@DevCharly fyi, the problem in NetBeans seems to be at https://github.com/apache/netbeans/blob/master/java/java.source.base/src/org/netbeans/modules/java/source/parsing/CachingFileManager.java#L272  This is using the fully qualified name without extension as a map key when parsing multi-release JARs. Just experimenting with a quick fix.

**Comment by DevCharly** [comment]
Just released version 0.34 that includes a workaround for this issue (reorder files in JAR).
So FlatLaf 0.34 can be used in NetBeans 11.3 (and older) without errors.

**Comment by sstephans** [comment]
I'm having the same compiler error issue. 
This line `UIManager.setLookAndFeel(new FlatLightLaf());` as well as `FlatLightLaf.install()` both produce the error

```
java: cannot find symbol
symbol: class FlatLightLaf
```

Including the statement `import com.formdev.flatlaf.FlatLightLaf;` produces the error
`java package com.formdev.flatlaf does not exist`

I'm running the IntelliJ IDE, Java version 8, using gradle build tools. I have this line in my gradle build dependencies
`runtime group: 'com.formdev', name: 'flatlaf', version: '0.35'`

Every time I refresh gradle, it shows the package in my list of runtime and test runtime dependencies. I have also tried versions 0.32-0.35 and all produce the same error when compiling.

**Comment by thisisleobro** [comment]
I am having the same issue using flatlaf with gradle, eclipse and java 11 by adoptopenjdk. I am using windows 10 i685, Building and running works fine. i also can run the build jar in folder /build/libs/nameofjar.jar from the command line but code-completion does not work. Eclipse says it cant resolve symbols `import com.formdev.flatlaf.FlatDarkLaf;` and `FlatDarkLaf.install();`.
How should i procede?

**Comment by DevCharly** [comment]
@sstephans `runtime` in gradle build dependencies adds FlatLaf only for running the application, but not for compiling.

Use `implementation` instead of `runtime`.

Issue #168 might be also provide useful information.
