### ISSUE TITLE
Empty tooltips showing on screen

### ISSUE THREAD

**Issue by Nibby** [JFormDesigner/FlatLaf#134]
When a component has an empty tooltip set, an empty tooltip bubble is drawn. For example:
```java 
JButton c = new JButton("Tooltip Test");
c.setToolTipText("");
```
![Screen Shot 2020-07-28 at 11 44 52 AM](https://user-images.githubusercontent.com/1026658/88602861-c1feec00-d0c7-11ea-9e6e-be50e740e99a.png)

Setting the tooltip text to `null` disables this. This is quite different form other LaFs, where an empty tooltip is not shown.

**Comment by Poivin** [comment]
Yes i noticed that too. in my app i have tooltips with empty string inside and they were invisible before using flatLAF.

**Comment by DevCharly** [comment]
Thx for reporting. I agree that is does not make any sense to show empty tips. This is now fixed in master branch.

But this is actually a problem in Swing because it always creates a JToolTip as soon as `JComponent.getToolTipText() != null`.
(see https://github.com/openjdk/jdk/blob/bcff4990ad9db20d11c59841a409717118645a65/src/java.desktop/share/classes/javax/swing/ToolTipManager.java#L691-L694). So the only chance to "hide" the empty tooltip was setting its preferred size to 0,0.

I wonder what LaFs you're using that do not show empty tips. I tried Metal, Nimbus, Substance, Windows and Mac L&F and all showed empty tips...

**Comment by Poivin** [comment]
Thx DevCharly!
I used Motif LaF and juste verified it again with the same code.

**Comment by DevCharly** [comment]
@Poivin maybe you did not notice it because is is a small dot hidden by the mouse pointer. Move the mouse slightly to the right and you probably see it (Java 8):

![grafik](https://user-images.githubusercontent.com/5604048/88813335-159d3280-d1b9-11ea-98f0-94f66c41223a.png)

Windows LaF (Java 8):
![grafik](https://user-images.githubusercontent.com/5604048/88813559-5eed8200-d1b9-11ea-8405-50ecaed739d8.png)

In Java 14 the empty tips are much larger and not hidden by the mouse pointer:
![grafik](https://user-images.githubusercontent.com/5604048/88813785-a542e100-d1b9-11ea-9938-ea6549ce5539.png)
![grafik](https://user-images.githubusercontent.com/5604048/88813818-ab38c200-d1b9-11ea-9fd9-8a363e5e6ff6.png)

**Comment by DevCharly** [comment]
So generally I would recommend using `null` for toolTipText instead of empty strings 😉
