### ISSUE TITLE
JTree incorrect highlight when lost focus

### ISSUE THREAD

**Issue by Makishima** [JFormDesigner/FlatLaf#136]
Hello!
We are using JTree with HTML decoration. When window lost focus selected element highlights in the wrong way.
In focus
![изображение](https://user-images.githubusercontent.com/5548003/88834205-2612d480-d1dc-11ea-98b2-523cbfc9ce50.png)
Lost focus
![изображение](https://user-images.githubusercontent.com/5548003/88834226-2e6b0f80-d1dc-11ea-8772-b6b22c269a2d.png)

**Comment by DevCharly** [comment]
Hmm, this works fine with default tree cell renderer. Could be related to the renderer you're using.
Is this NetBeans Platform?

FlatLaf changes the color of the tree cell renderer while painting. If either invokes `DefaultTreeCellRenderer.setBackgroundSelectionColor(Color)` or `Component.setBackground(Color)` on the renderer, but only if it has default selection color. See:
https://github.com/JFormDesigner/FlatLaf/blob/7057e3c6ad123de451f6d2e73eea7c84956d1a1f/flatlaf-core/src/main/java/com/formdev/flatlaf/ui/FlatTreeUI.java#L264-L278

Please check/debug what your renderer does.

A test code and/or more details would be useful.

**Comment by dinix2008** [comment]
@DevCharly, hello!

it reminded me of the https://issues.apache.org/jira/browse/NETBEANS-4173 problem that never made it into the Netbeans fix (https://github.com/apache/netbeans/pull/2079). I have now returned to it and tested it - no error. If this cannot be fixed by means of FlatLaf, then I will have to offer them my fix for Netbeans again.

No fixes in org.openide.awt.HtmlRendererImpl

<img width="871" alt="Снимок экрана 2020-07-31 в 09 24 53" src="https://user-images.githubusercontent.com/1597289/89006673-eb11bd80-d30f-11ea-95a3-3758fdb52a16.png">

With fixes in org.openide.awt.HtmlRendererImpl

<img width="916" alt="Снимок экрана 2020-07-31 в 09 25 22" src="https://user-images.githubusercontent.com/1597289/89006702-fc5aca00-d30f-11ea-8e28-ec46107e7d0f.png">

**Comment by dinix2008** [comment]
@DevCharly 
I made corrections to FlatTreeUI
https://github.com/JFormDesigner/FlatLaf/pull/144

The error no longer manifests itself

**Comment by dinix2008** [comment]
Sorry, when testing in Netbeans itself and not a synthetic example, the error is reproduced again. Removed pull request.

**Comment by Makishima** [comment]
@DevCharly We found out that the problem is in our code. Thanks for response
