### ISSUE TITLE
MenuItem accelerator text is unconventional on macOS

### ISSUE THREAD

**Issue by Nibby** [JFormDesigner/FlatLaf#141]
Only tested on macOS. The menu item accelerator text has an extra plus character. It seems to be hard-coded in AWT. This is not coherent with the shortcut key style used natively.

For example, this menu item has a shortcut key of **Command + Shift + N**, but it is rendered as 
<img width="65" alt="Screen Shot 2020-07-31 at 1 48 39 PM" src="https://user-images.githubusercontent.com/1026658/88991344-8ae14280-d334-11ea-8cbc-fd74f4fef6a2.png">

Which, for the less technical folks, may be misunderstood as Command + Plus + Shift + N.

**Comment by DevCharly** [comment]
Thx 👍 

Fixed in master branch.

The order of the option keys was also wrong on macOS (not the same as in native macOS apps).
On native macOS the Control key is always first and the Command key the last option key.
For right-to-left orientation, the whole accelerator is now reversed on macOS (as in Aqua LaF).

**Comment by Nibby** [comment]
Thanks for your prompt responses as always.
