### ISSUE TITLE
HTML-formatted tooltip is truncated on HiDPI display 

### ISSUE THREAD

**Issue by Nibby** [JFormDesigner/FlatLaf#142]
Tested on a Windows 10 OS using AdoptOpenJDK 11.0.6 at 3x scale factor. The last word in the tooltip has been cut off. The last word in this tooltip is 'found'. It seems like the manual tooltip width correction isn't enough?

<img width="632" alt="Screen Shot 2020-07-31 at 1 51 51 PM" src="https://user-images.githubusercontent.com/1026658/88991509-fdeab900-d334-11ea-8fb7-33d1dbb526de.png">

**Comment by DevCharly** [comment]
Yes, seems that the view area is too small and the last word is wrapped to the next line...

Happens also in Windows LaF (Java 11 at 150%):

![image](https://user-images.githubusercontent.com/5604048/89039054-b880b880-d341-11ea-90b3-f711db6c0d43.png)

But works in Java 8:

![image](https://user-images.githubusercontent.com/5604048/89039007-a56de880-d341-11ea-8948-7b09f6150434.png)

**Comment by DevCharly** [comment]
Strange, when I invoke `super.getPreferredSize( c )` from `FlatToolTipUI.paint(g, c)` it returns larger width than when invoked from `javax.swing.ToolTipManager`. This is probably the reason for truncating. The question is, why does this happen?

**Comment by Nibby** [comment]
A bug was logged and resolved in OpenJDK's database: https://bugs.openjdk.java.net/browse/JDK-8213535

It appears the bug was introduced sometime in JDK 10 and the fix is scheduled for JDK 16.

**Comment by DevCharly** [comment]
@Nibby thx for the pointer to the bug. 

The problem seems that the `JToolTip` does not have a `GraphicsConfiguration` when `BasicToolTipUI.getPreferredSize(c)` is invoked from `ToolTipManager`. Then the created `FontMetrics` has a `FontRenderContext` where the `AffineTransform tx` is `null`.
See [SwingUtilities2.getFRCProperty()](https://github.com/openjdk/jdk/blob/4cab73112c6a00221d68d2be6f1fbd998815a06c/src/java.desktop/share/classes/sun/swing/SwingUtilities2.java#L1250-L1259). This results in too small character widths and in too small tooltip width.

Here is a little program to demonstrate this:

~~~java
import java.awt.EventQueue;
import java.awt.Font;
import java.awt.FontMetrics;
import javax.swing.JFrame;
import javax.swing.JLabel;

public class HiDPIFontMetricsTest
{
	public static void main( String[] args ) {
		System.setProperty( "sun.java2d.uiScale", "2" );

		EventQueue.invokeLater( () -> {
			JFrame frame = new JFrame();
			frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
			frame.add( new MyLabel() );
			frame.setVisible( true );
		} );
	}

	private static class MyLabel extends JLabel {
		public MyLabel() {
			setFont( new Font( "Segoe UI", Font.PLAIN, 12 ) );
			test();
		}

		@Override
		public void addNotify() {
			super.addNotify();
			test();
		}

		private void test() {
			FontMetrics fm = getFontMetrics( getFont() );
			int w = fm.stringWidth( "1" );

			System.out.println( "----------------" );
			System.out.println( w );
			System.out.println( fm );
			System.out.println( fm.getFontRenderContext().getTransform() );
		}
	}
}
~~~

Outputs character width `6` if the label does not have a `GraphicsConfiguration` (invoked from constructor)
and `7` if it has (invoked from `addNotify()`) (with Java 14):
~~~
----------------
6
sun.font.FontDesignMetrics[font=java.awt.Font[family=Segoe UI,name=Segoe UI,style=plain,size=12]ascent=13, descent=3, height=16]
AffineTransform[[1.0, 0.0, 0.0], [0.0, 1.0, 0.0]]
----------------
7
sun.font.FontDesignMetrics[font=java.awt.Font[family=Segoe UI,name=Segoe UI,style=plain,size=12]ascent=13, descent=3, height=16]
AffineTransform[[2.0, 0.0, 0.0], [0.0, 2.0, 0.0]]
~~~

**Comment by DevCharly** [comment]
Finally fixed in master branch
