### ISSUE TITLE
Colors in the tooltips of disabled buttons

### ISSUE THREAD

**Issue by lbalazscs** [JFormDesigner/FlatLaf#15]
I am using FlatDarculaLaf with version 0.14 from Maven, and I noticed that the tooltips of disabled buttons are using a bright yellow background and dark text, and this attracts the eye, while anything disabled should _not_ attract it. The "real" Darcula from Intellij uses the same colors for tooltips of disabled buttons as for the enabled ones, and this is OK.

BTW the "real" Darcula has cool little triangles in the tooltip shapes pointing to the original mouse location, while FlatDarculaLaf doesn't have them, but this is not so important.

**Comment by DevCharly** [comment]
Thanks. This is a bug. Actually didn't know that tooltip can have different colors for disabled components. Using Swing since 20 years and still learning...  😉 

Yes, the "real" Darcula tooltips look very nice, but I wanted to keep the initial implementation as simple as possible. Maybe I'll add them later...

**Comment by JFormDesigner** [comment]
thanks, fixed in 0.14

I've also improved the styling a little bit. Hope you like it.

**Comment by lbalazscs** [comment]
The colors are great now!
