### ISSUE TITLE
Global icon scaling for components

### ISSUE THREAD

**Issue by schliepRon** [JFormDesigner/FlatLaf#154]
Hey,

this is no problem with flatlaf but maybe you got an idea how to solve it:

-------------------
background information

I`m implementing FlatLaf in the swing-framework of the company im working for.

We decided to renew our icons aswell and the old ones were 16x16, 32x32 or similar.
Now we want to use higher resolution or even svg. 

Our applications which use our framework are pretty big with lots of modules. 

--------------------------

Because changing the scaling of the icons on every component manually would be an enormous expenditure of time id like to do this within the UI classes.

For FlatLaf its pretty easy but our framework should still be able to support the native WindowsLAF etc.
But the native UI classes aren`t exported.

Any idea how to do this in a smart way?

**Comment by DevCharly** [comment]
Not sure whether I understood your exact problem correctly, so here are some common thoughts...

You probably need some `javax.swing.Icon` implementation that automatically loads needed icons (depending on scale factor and light/dark theme; e.g. dark 16x16 or light 32x32) and then paints them scaled (if necessary).

For flexibility it is probably best to have some kind of "icon loader" class. Then you can easy change the implementation, at a single place, if necessary. E.g:
~~~java
public class IconLoader {
    public static Icon getIcon( String resourceName ) {
        return new MyIcon( resourceName );
    }
}
~~~

Then you set the icon on the component (e.g. `myLabel.setIcon( IconLoader.getIcon( "com/pkg/someIcon.svg" )`) and the icon class then does the rest.

## SVG

If you have the chance to use SVG then go for it.
SVG has many advantages compared to bitmaps.
A single .svg (best in 16x16 size) works for all scaling factors.
Colors can be changed on the fly for dark themes or disabled icons.

The [flatlaf-extras](https://github.com/JFormDesigner/FlatLaf/tree/master/flatlaf-extras) subproject provides the class `FlatSVGIcon` that uses svgSalamander to render. `FlatSVGIcon` paints scaled (if necessary), can replace colors depending on theme and can paint disabled icons. This class also works in other LaFs (e.g. Windows LaF)

This is from FlatLaf Demo ("Extras" tab) and demonstrates how themes change SVG icon colors:
![svgicon](https://user-images.githubusercontent.com/5604048/89644189-a8c02180-d8b7-11ea-8492-c69ba3113749.gif)

The idea is to use only a well defined set of colors in SVG icons and
then replace them at runtime to dark variants (or to other theme colors).
Then a single SVG icon (light variant) can be used for dark themes too.
IntelliJ Platform uses this mechanism to allow themes to change IntelliJ Platform icons.

The colors FlatLaf maps to dark variants are based on IntelliJ Platform [Action icons](https://jetbrains.design/intellij/principles/icons/#action-icons).
Use colors from the left column in SVG, then they are mapped to the colors in right column in dark themes.

There is also a color palette for [Noun/Object icons](https://jetbrains.design/intellij/principles/icons/#noun-icons) defined, but these colors are not mapped to dark variants. But those colors may be replaced by IntelliJ platform themes (as shown in above video).

You can also add custom color mappings to `FlatSVGIcon` with:
~~~java
FlatSVGIcon.ColorFilter.getInstance().add( fromColor, toColor );
~~~

To create SVG icons I can recommend [Sketch](https://www.sketch.com/) (requires macOS) with SVGO plugin.
But there are also other tools available.

You could also use SVG icons from [IntelliJ Platform](https://github.com/JetBrains/intellij-community/) (Apache licensed).
Here is a site where it is possible to search for those icons: https://jetbrains.github.io/ui/resources/icons_list/

## PNG/GIF

With bitmap images it is more complicated. For HiDPI you need at least two size variants (1x and 2x). If you want use dark themes, then maybe two additional bitmaps if the light variants look bad on dark background.
When painting, you have to choose the right bitmap, maybe scale it (e.g. for 1.5x) and then paint it.

In FlatLaf there is class [ScaledImageIcon](https://github.com/JFormDesigner/FlatLaf/blob/master/flatlaf-core/src/main/java/com/formdev/flatlaf/util/ScaledImageIcon.java), which takes a **single** bitmap image, scales it (automatically choosing best scaling method) and paints it. This class supports multi-resolution images available since Java 9 (see `java.awt.image.MultiResolutionImage` and subclasses).

There is also class [FlatTitlePaneIcon](https://github.com/JFormDesigner/FlatLaf/blob/master/flatlaf-core/src/main/java/com/formdev/flatlaf/ui/FlatTitlePaneIcon.java), a subclass of `ScaledImageIcon` that takes **multiple** bitmap images and chooses the best image for painting. This class is used for custom window decorations if the window provides multiple resolutions of the window title icon. The downside of using this class is that it is necessary to preload bitmap images in all resolutions even if they are never used.

`ScaledImageIcon` and `FlatTitlePaneIcon` do not support dark variants, but work in all LaFs.

## Conclusion

There are already some useful classes for SVG or PNG icons in FlatLaf, which can be used with any LaF, but a general purpose icon loader, that puts the pieces together, is missing.

**Comment by schliepRon** [comment]
Thank you for your answer :)
