### ISSUE TITLE
Windows: Snap to left/right half of screen not working

### ISSUE THREAD

**Issue by erl987** [JFormDesigner/FlatLaf#170]
Hi,

if you take the FlatLaf demo app (or some real-world application using FlatLaf), it is not possible to *snap the application to the left or right half of the screen* (using `Windows Key` + `Left Arrow`, etc.).

This would be a great enhancement to consider in the further development of FlatLaf.

Best regards,
Ralf

**Comment by stanio** [comment]
I've noticed this happens when painting windows decorations is on (which is by default for the demo).  If one unchecks Options / Windows decorations, snapping gets working.

**Comment by DevCharly** [comment]
Yes, happens only if FlatLaf **custom window decorations** are enabled.

This is a feature of Windows 10, which is unfortunately not available for undecorated frames in Java (used for custom window decorations). So even if I implement e.g. `Windows+Left` keys in FlatLaf and resize the window to fill the left half of the screen, this would not show the other open windows as icons on the right half of the screen...

There is an article that solves this by using Java Native Access (JNA):
https://medium.com/swlh/customizing-the-title-bar-of-an-application-window-50a4ac3ed27e
But this is no option for core FlatLaf because the necessary library dependencies are 4-5 MB.
Maybe this can be done in a FlatLaf subproject...

An option that already works is to **use JetBrains Runtime 11** to run own application:
https://confluence.jetbrains.com/display/JBR/JetBrains+Runtime
JetBrains Runtime (JBR) is based on OpenJDK and powers IntelliJ IDEA and other JetBrains IDEs.
JBR supports native Windows features for undecorated frames and FlatLaf supports JBR.
So even if FlatLaf custom window decorations are enabled, application window behaves like native window.

Hope that JBR custom window decorations are ported to OpenJDK in the future...

**Comment by erl987** [comment]
Thanks, we go for switching off the custom window decorations - at least for now. Using Java 11 is not really an option for us.

Cheers,
Ralf

**Comment by DevCharly** [comment]
There is now a fix available in PR #267 
Would be great if you could try it out in your app.
Thx.

**Comment by erl987** [comment]
Great! We will test this as soon as possible!

**Comment by DevCharly** [comment]
now fixed in main branch

**Comment by erl987** [comment]
I can confirm that the application is now working as expected with FlatLaf 1.1.

Thanks for the great work!
