### ISSUE TITLE
Popup menu shows on adjacent monitor

### ISSUE THREAD

**Issue by stanio** [JFormDesigner/FlatLaf#177]
FlatLaf 0.42
Java 11
Windows 10

**Steps to reproduce**

Have a two-monitor (left and right) setup.  Open and maximize the FlatLaf Demo (or another application with a menu-bar) on the ride-side monitor.  Start cycling through top-level menus.

**Actual results**

Some of the (popup) menus get shown on the other (left-side) monitor for no apparent reason.

**Details**

So far I'm experiencing this with two configurations:

Left monitor: 150%
Right monitor (primary): 200%

Left monitor (primary): 125%
Right monitor: 150%

Maybe the right one should have a greater scaling factor to reproduce as I'm not getting it with:

Left monitor: 150%
Right monitor (primary): 125%

Appears to happen with FlatLaf Demo 0.35 as well.  Some of the menus may not show on the other monitor but appear to be aligned on the right-side:

![right-aligned-menu](https://user-images.githubusercontent.com/1247730/93744687-ed4f1480-fbfa-11ea-87e5-2f50893de7a9.png)

When showing the window on the left-side monitor, the problem is not visible and all menus are left-aligned:

![left-aligned-menu](https://user-images.githubusercontent.com/1247730/93744789-17a0d200-fbfb-11ea-9677-74b764e1b4d1.png)

Happens with both "Window decorations" enabled and disabled.

**Comment by stanio** [comment]
> Some of the menus may not show on the other monitor but appear to be aligned on the right-side

I'm seeing this only with the 125%, 150% (left, right) monitor configuration, so far.

**Comment by DevCharly** [comment]
Hmm, strange. Can not reproduce it...

Does this also happen with Metal or Windows LaFs?
You can switch to those LaFs in FlatLaf Demo using the bottom-left combobox.

What Java distro do you use? AdoptOpenJDK? Or other?

Could you please run [FlatScreenInfo.java](https://github.com/JFormDesigner/FlatLaf/blob/master/flatlaf-testing/src/main/java/com/formdev/flatlaf/testing/FlatScreenInfo.java) on your computer, with the same Java version, and post the output here?
This program outputs detailed information about the connected screens.
With this information I can configure the same setup an try to reproduce the issue.
All you need to run the program is `FlatScreenInfo.java` because it does not have any dependencies.

**Comment by stanio** [comment]
Should have tried this already before – appears to happen with Metal and the Windows LaFs as well, so it doesn't appear FlatLaf specific.

I'm using Oracle's JDK.  Here are the FlatScreenInfo outputs:


```
Scale factors:  200% / 150%
Java version:   11.0.7

ID:      \Display0 (main)
Size:    2880 x 1620 / 32 Bit / 60 Hz
Bounds:  1440 x 810 / x 0 / y 0   (scale -2.0)
Insets:  left 0 / right 0 / top 0 / bottom 80
Scale:   2.0

ID:      \Display1
Size:    1920 x 1080 / 32 Bit / 60 Hz
Bounds:  1280 x 720 / x -1280 / y -177   (scale -1.5)
Insets:  left 0 / right 0 / top 0 / bottom 0
Scale:   1.5
```

```
Scale factors:  125% / 150%
Java version:   11.0.7

ID:      \Display0 (main)
Size:    1920 x 1080 / 32 Bit / 60 Hz
Bounds:  1536 x 864 / x 0 / y 0   (scale -1.25)
Insets:  left 0 / right 0 / top 0 / bottom 50
Scale:   1.25

ID:      \Display1
Size:    1920 x 1080 / 32 Bit / 60 Hz
Bounds:  1280 x 720 / x 1280 / y 0   (scale -1.5)
Insets:  left 0 / right 0 / top 0 / bottom 0
Scale:   1.5
```

I'll try to update to JDK 11.0.8 to see if it would make any difference... but then it doesn't appear a FlatLaf problem.

**Comment by DevCharly** [comment]
Ok, can now reproduce it with your second screen configuration.

Occurs also in Oracle JDK 11.0.8 and in AdoptOpenJDK 11.0.8.
And also in OpenJDK 14.0.2 and 15.

But works in JetBrains Runtime 11.0.8 (bundled in IDEA 2020.2.2)

**Comment by stanio** [comment]
Thanks for looking into it.  Please, close at your discretion.

**Comment by DevCharly** [comment]
Just compared screen info of Oracle JDK with JetBrains Runtime:

![image](https://user-images.githubusercontent.com/5604048/94014730-385c5980-fdac-11ea-96d8-13c9d754fcf1.png)

The interesting thing is the difference in the X location of the second screen.
In Oracle JDK it is `1280`, but the width of the first screen is `1536`.
So the first screen partly overlaps the second screen in virtual coordinate system!

In JetBrains Runtime the X location of second screen is `1920` and the two screens do not overlap. This is better, but also strange because in virtual coordinate system I would expect `1536`...

The wrong menu positioning happens in method `JMenu.getPopupMenuOrigin()`, which first searches for a screen that contains the popup x/y coordinates and then corrects x/y so that the popup fits into the screen. In case of "overlapping" screens, the first screen is found and x is made smaller...

This has actually nothing to do with maximized windows. Occurs also in not maximized windows:

![image](https://user-images.githubusercontent.com/5604048/94019311-e9b1be00-fdb1-11ea-8b7c-464260ac1c04.png)

Also occurs for other popups. E.g. comboboxes:

![image](https://user-images.githubusercontent.com/5604048/94019503-2b426900-fdb2-11ea-9ca6-4d4f9b007a9a.png)

**Comment by stanio** [comment]
> In JetBrains Runtime the X location of second screen is `1920` and the two screens do not overlap. This is better, but also strange because in virtual coordinate system I would expect `1536`...

Yeah, I would expect `1536` for the second monitor offset as well.  I see the bounds reported are in _virtual_ (_screen_?) coordinates (according to the width and height reported) but the [`GraphicsConfiguration.getBounds()`](https://docs.oracle.com/en/java/javase/11/docs/api/java.desktop/java/awt/GraphicsConfiguration.html#getBounds%28%29) is confusing:

> Returns the bounds of the `GraphicsConfiguration` in the device coordinates.

I guess _device_ coordinates should match the physical size reported but then it would be "impossible" to correctly position stuff.

**Comment by DevCharly** [comment]
Yea, that's confusing. The documentation is not clear IMHO...

**Comment by grimlock81** [comment]
I think it's related to this OpenJDK issue https://github.com/openjdk/jdk/pull/375

**Comment by DevCharly** [comment]
@grimlock81 thx for the link. Good news that a fix is (hopefully) coming to Java 16...

Here is the JDK issue: https://bugs.openjdk.java.net/browse/JDK-8211999
