### ISSUE TITLE
Maximized app does maximize when moving to the secondary screen

### ISSUE THREAD

**Issue by erl987** [JFormDesigner/FlatLaf#180]
Hi,

I experience the following problem on Windows 10:

* take the `FlatFlaf`-demo app and disable the *Window Decorations* via the Options menu
* maximize the app on the primary 4k-screen
* now move it to the secondary screen with the keyboard: `Win` + `Shift` + `Right arrow`

=> it will move to the secondary screen but will not be maximized

My screen setup is as follows:
Scale factors: 250% / 125%
Java version: 14.0.2

ID: \Display0 (main)
Size: 3840 x 2160 / 32 Bit / 60 Hz
Bounds: 1536 x 864 / x 0 / y 0 (scale -2.5)
Insets: left 0 / right 0 / top 0 / bottom 100
Scale: 2.5

ID: \Display1
Size: 1920 x 1080 / 32 Bit / 59 Hz
Bounds: 1536 x 864 / x 3072 / y 0 (scale -1.25)
Insets: left 0 / right 0 / top 0 / bottom 50
Scale: 1.25

/Ralf

**Comment by stanio** [comment]
I've noticed this is a general Java behavior not specific to FlatLaf.  I don't know if FlatLaf could or should implement a workaround for this.

**Comment by erl987** [comment]
I get exactly the same behaviour in our own app if using FlatFlaf, but not if using the Metals or Windows L&F. So I think it has something to do with FlatLaf.

**Comment by stanio** [comment]
O.k.  I'm not getting the issue using Java 8, but I'm getting it using Java 11 and all built-in LaFs (metal and system/windows).  Don't have Java 14 to try.  I guess it is related to the `GraphicsConfiguration.getBounds()` returning sizes in _user_ coordinates rather than _device_ coordinates as officially documented (#177).

I think <kbd>Win + Shift + Right arrow</kbd> is not handled by any LnF (although it might have changed in Java 14, unlikely given Oracle does not invest in Swing anymore).  As far as I've tried, no (java.awt) window events get dispatched when moving the window this way.  I guess one may detect the window has moved screens by listening for `graphicsConfiguration` property changes and re-apply the maximized state:

```java
    Window window;
    ...
    addPropertyChangeListener("graphicsConfiguration", evt -> {
        int state = window.getExtendedState();
        window.setExtendedState(0);
        SwingUtilities.invokeLater(() -> window.setExtendedState(state));
    });
```

This appears similar (not related to FlatLaf):

-   https://sourceforge.net/p/squirrel-sql/git/merge-requests/54/

**Comment by erl987** [comment]
You are actually right, I checked that again and it *does* happen with Windows and Metal L&F as well!

**Comment by DevCharly** [comment]
Looks like a scaling related bug in JDK.

It works fine if both screens use same scale factor. 

If scale factors are different, the window is moved to secondary screen and **remains in maximized state** (see mid icon in top-right window title pane), but the window bounds do not fill the screen.

If the secondary screen uses a smaller scale factor than the primary screen, the window becomes smaller than secondary screen.
If the secondary screen uses a larger scale factor than the primary screen, the window becomes larger than secondary screen and is partly outside of screen...

There are a lot of scaling related changes in OpenJDK PR https://github.com/openjdk/jdk/pull/375
Hopefully the PR also fix this issue...

BTW also tested [JetBrains Runtime 11](https://confluence.jetbrains.com/display/JBR/JetBrains+Runtime) and it works perfect with this JRE.
