### ISSUE TITLE
Regression: Popups using JToolTip components do not respect their location

### ISSUE THREAD

**Issue by Chrriis** [JFormDesigner/FlatLaf#188]
While testing the new features (sorry @DevCharly, I did not have much time to do it earlier!) I stumbled upon this major regression for us: the location of a popup is not respected:
![DataTipsOffset](https://user-images.githubusercontent.com/1174202/96095684-3b3ffb00-0ecf-11eb-9fab-bf263d914945.png)
It seems that the use of JToolTip is a problem. If I replace with a JPanel, then the position is correct (but not the look).

Here is the test case:
[TableTestWithTip.zip](https://github.com/JFormDesigner/FlatLaf/files/5383339/TableTestWithTip.zip)

(another problem shown in this test case: "table.setShowGrid(true)" is not respected by the boolean column. Should I open a bug?)

**Comment by DevCharly** [comment]
Sorry, commit 8925c27eb92ec0de3ed0de045c666d2503da789c (fix for #164) is responsible for the wrong tooltip location.
Working on a solution...

**Comment by DevCharly** [comment]
Regarding missing grid lines in boolean column: this is normal because table intercell spacing is set to 0,0 in FlatLaf to avoid gaps in selection:

![image](https://user-images.githubusercontent.com/5604048/96140566-5d9e3c80-0f00-11eb-8d88-71b7e97dd4cd.png)

You should also set intercell spacing if showing grid:
~~~java
table.setIntercellSpacing( new Dimension( 1, 1 ) );
~~~
