### ISSUE TITLE
Disabled JLabel with FlatSVGIcon is not shown if disabledIcon not set

### ISSUE THREAD

**Issue by electriq** [JFormDesigner/FlatLaf#205]
I have found that a JLabel with FlatSVGIcon is not drawn at all and has zero size if label.setEnabled(false) was set. Experimentally found a workaround: manual setting of the disabled icon for the label. I never have to set disabled icon with simple ImageIcon with BufferedImage, so it seems to be a bug. I currently don't understand the cause because there is no such problems with disabled JButtons with FlatSVGIcon and I see that JLabel uses the same UIManager.getLookAndFeel().getDisabledIcon(this, defaultIcon) method as JButton. Checked on AdoptOpenJDK 15.0.1.9 (hotspot).

Minimal test code:

```
public static void main(String[] args) {
        Icon icon = new FlatSVGIcon("image.svg");
        JLabel label = new JLabel(icon);
        
//        label.setDisabledIcon(icon); // Workaround: uncomment this
        label.setEnabled(false);

        JFrame mainFrame = new JFrame("Disabled JLabel with FlatSVGIcon");
        mainFrame.getContentPane().add(label);
        mainFrame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        mainFrame.setSize(400, 200);
        mainFrame.setVisible(true);
    }
```

**Comment by electriq** [comment]
The other strange thing is that when I set FlatSVGIcon also as the `disabledIcon` for a JLabel or JButton, then when the component is disabled, the `disabledIcon`  is shown grayed out like the single `defaultIcon` if the disabled one was not set. But the ImageIcon(BufferedImage) disabled icon is shown as is, not grayed out. This is not FlatLAF-specific, the same behavior can be seen with the default Metal LnF. I have looked briefly the code of JLabel and JButton/AbstractButton and did not find currently where the `disabledIcon` is processed to the gray one.

This behavior is not an issue for our project because we don't need the setting of separate disabled icon anywhere, but if I use `label.setDisabledIcon(theSameIcon);` as a workaround and the grayed behavior will be changed to the normal sometime, the disabled label will be shown as enabled with the same enabled icon.

**Comment by DevCharly** [comment]
Many thx for reporting this issue.

Seems that my idea of painting disabled SVG icons using `c.isEnabled()` does not work for labels and other LaFs.

https://github.com/JFormDesigner/FlatLaf/blob/c67ba028393934f95fc05295082e42e42dc701f4/flatlaf-extras/src/main/java/com/formdev/flatlaf/extras/FlatSVGIcon.java#L267-L272

The problem is that `FlatSVGIcon` does not extend `javax.swing.ImageIcon` (since 464787dc1e0495a695d03525d11fa036a80f3872).
Then `LookAndFeel.getDisabledIcon()` returns `null` and the label assumes that there is no icon.

Button behaves different because is simply uses "enabled" icon if `LookAndFeel.getDisabledIcon()` returns `null`.

I probably could fix this in `FlatLabelUI`, but to make `FlatSVGIcon` work as expected in any Laf it is better to extend `ImageIcon`.

**Comment by DevCharly** [comment]
Changed in master branch.

`FlatSVGIcon` now again implements `ImageIcon`, which enables auto-creation of disabled icons in other LaFs.
(based on multi-resolution bitmap images)

When a FlatLaf theme is active, disabled icons still use vector drawing.
