### ISSUE TITLE
JTabbedPane related exceptions when retrieving components

### ISSUE THREAD

**Issue by j-dimension** [JFormDesigner/FlatLaf#219]
Hi, I am trying to upgrade from FlatLaf 0.38 to 0.44 and some of my code started throwing exceptions. 

I am using tabbed panes and in some places I iterate over its components. I have a feeling that - maybe related to the close button being added - the tabbed panes #getComponentAt and #getTabComonentAt started behaving weirdly.

Even with a minimal example - a tabbed pane with two (empty) JPanels - this is what happens:

```
        for (int f = 1; f < this.jTabbedPane1.getTabCount(); f++) {
            // throws NPE
            JPanel fip = (JPanel) this.jTabbedPane1.getTabComponentAt(f);
            System.out.println(fip.getClass().getName());
        }
        
        for (int f = 1; f < this.jTabbedPane1.getComponentCount(); f++) {
            //java.lang.IndexOutOfBoundsException: Index: 2, Size: 2
            JPanel fip = (JPanel) this.jTabbedPane1.getComponentAt(f);
            System.out.println(fip.getClass().getName());
        }
```

Just as a side note (not relevant here) - I am iterating from index 1 because I am never interested in the first tab (with index 0).

Am I misusing the API?

**Comment by j-dimension** [comment]
Here's the stack trace for the second case:

```
Exception in thread "AWT-EventQueue-0" java.lang.IndexOutOfBoundsException: Index: 2, Size: 2
	at java.util.ArrayList.rangeCheck(ArrayList.java:659)
	at java.util.ArrayList.get(ArrayList.java:435)
	at javax.swing.JTabbedPane.getComponentAt(JTabbedPane.java:1224)
	at TabFrame.<init>(TabFrame.java:692)
```

**Comment by j-dimension** [comment]
in a tabbed pane with two panels / tabs
- #getTabCount returns 2 but is giving NPEs
- #getComponentCount returns 3 but yields IndexOutOfBoundsException when retrieving index 2

**Comment by j-dimension** [comment]
For #getComponentAt, I used to only see the JPanel objects added to the tabbed pane. Now I am also getting an instance of FlatTabbedPaneUI$TabCloseButton

Therefore, the issues I am seeing might be related to the added close button, but I am not sure and it baffles me that I am not seeing any flatlaf classes in the stacktrace.

**Comment by DevCharly** [comment]
In first loop, replacing `jTabbedPane1.getTabComponentAt(f)` with `jTabbedPane1.getComponentAt(f)` should fix the NPE.
In second loop, replacing `jTabbedPane1.getComponentCount()` with `jTabbedPane1.getTabCount()` should fix the exception.

If you iterate over tabs (e.g. using `getComponentAt()`) always use `getTabCount()`.
Do not use `getComponentCount()` for `JTabbedPane` because it may contain more components than tabs.
E.g. close button, button for "show hidden tabs" popup.

**Comment by DevCharly** [comment]
If you use tab scroll layout, there are even more components as direct children of the tabbed pane:
buttons for scrolling and a `JViewport` that contains the tabs.

**Comment by j-dimension** [comment]
Thank you so much for the quick response, @DevCharly !

So now I have this:

```
        for (int f = 1; f < this.tabPaneForms.getTabCount(); f++) {
            FormInstancePanel fip = (FormInstancePanel) this.tabPaneForms.getComponentAt(f);
            fip.save();
        }
```

So I am supposed to loop based on **tab** count, but retrieve the panels using **getComponentAt** - right?
This is crazy, I might have been doing it wrong for years! How embarassing...

**Comment by DevCharly** [comment]
> So I am supposed to loop based on tab count, but retrieve the panels using getComponentAt - right?

Yes, because `JTabbedPane.getComponentAt( int index )` is not the same as `Container.getComponent( int index )`.
The tabbed pane API is confusing...
Can't remember how often I (or IDE autocomplete) used by accident `JTabbedPane.getTabComponentAt()`...

> This is crazy, I might have been doing it wrong for years! How embarassing...

If it worked, it was not (completely) wrong 😉 😄 

Anyway thanks for pointing out this incompatibility.
I will change this so that the close button is only added when needed.
Then such problems should not occur.

**Comment by j-dimension** [comment]
Thanks for taking the time, @DevCharly 
I learnt a lesson. Closing the ticket.
