### ISSUE TITLE
Usage of SwingX PromptSupport grays out text fields

### ISSUE THREAD

**Issue by Bios-Marcel** [JFormDesigner/FlatLaf#223]
![bug1](https://user-images.githubusercontent.com/19377618/101987274-5cd11f00-3c93-11eb-839c-03903bc17370.png)
![bug2](https://user-images.githubusercontent.com/19377618/101987279-68bce100-3c93-11eb-8591-19d820f4fa89.png)

As soon as you type any text, the color is correct.

```java
import com.formdev.flatlaf.FlatLightLaf;
import org.jdesktop.swingx.prompt.PromptSupport;

import javax.swing.*;
import java.awt.*;

public class Main {
    public static void main(String[] args) {
        FlatLightLaf.install();

        JTextField a = new JTextField();
        PromptSupport.setPrompt("Prompt", a);
        JTextField b = new JTextField();

        JPanel layout = new JPanel(new FlowLayout());
        layout.add(a);
        layout.add(b);

        JFrame frame = new JFrame();
        frame.add(layout);
        frame.setSize(400, 200);
        frame.setLocationRelativeTo(null);
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        frame.setVisible(true);
    }
}
```

Dependencies:

```
    implementation 'com.formdev:flatlaf:0.45'
    implementation 'com.formdev:flatlaf-swingx:0.45'
    implementation 'org.swinglabs.swingx:swingx-all:1.6.5-1'
```

**Comment by DevCharly** [comment]
SwingX PromptSupport does some tricks that FlatLaf does not like.
It replaces text field UI delegate `FlatTextFieldUI` with own class `BuddyTextFieldUI`.
Also border `FlatTextBorder` is replaced with `BuddyLayoutAndBorder`.
Layout manager is replaced.
Seems to be very complicated and tricky...

This avoids that FlatLaf paint text field background.
Also if you enter text and use Flat IntelliJ or Darcula themes (with outside focus borders), the background is not correct:

![image](https://user-images.githubusercontent.com/5604048/101990172-9ca10200-3ca5-11eb-9b1a-5cfa9807c4f3.png)

Not sure whether this is fixable...


If you use FlatLaf only, I would recommend using placeholder texts instead:
~~~java
a.putClientProperty( "JTextField.placeholderText", "Prompt" );
~~~

![image](https://user-images.githubusercontent.com/5604048/101990227-0b7e5b00-3ca6-11eb-815d-f094998af322.png)

With next version 0.46, you can use `FlatTextField` from "extras" subproject:
~~~java
FlatTextField a = new FlatTextField();
a.setPlaceholderText( "Prompt" );
~~~

**Comment by Bios-Marcel** [comment]
Ah thanks for the info. Yeah, i don't know, but maybe we can fix it in swingx. We are actually using our own fork of swingx, so maybe there's something we can do.

**Comment by mwithake** [comment]
We have the same problem. We are also using the foreground color option to hint error messages in red (e.g. missing entries).
We are using PromptSupport directly in our derived JTextField class, so we could use the ClientProperty if FlatLaf is set instead of using PromptSupport but we are missing the color option.

**Comment by mwithake** [comment]
JXSearchField has the same problem when setting the prompt.

**Comment by DevCharly** [comment]
Had another look at the issue.
The problem is that `FlatTextFieldUI` background painting is **not invoked**.

`PromptSupport` replaces text field UI delegate `FlatTextFieldUI` with own class `BuddyTextFieldUI`,
which delegates painting to `FlatTextFieldUI`, but **only if text field is not empty**.
If empty, then it fills background itself if text field is opaque.
But in FlatLaf it is **not opaque**.

Here is the related code (in [PromptTextUI](https://github.com/isp-insoft-gmbh/SwingX/blob/673590dc2b68ff1f2ed1dcbed2d4f41389c815ff/swingx-core/src/main/java/org/jdesktop/swingx/plaf/PromptTextUI.java#L312-L318)):
~~~java
    public void update(Graphics g, JComponent c) {
        if (shouldPaintPrompt((JTextComponent) c)) {
            super.update(g, c);
        } else {
            delegate.update(g, c);
        }
    }
~~~

One solution would be to make text fields opaque if they use `PromptSupport`.
This works fine for themes "Flat Light" and "Flat Dark", but has issues with "IntelliJ/Darcual" themes (see my previous post).

Another solution would be to modify SwingX `PromptTextUI`.
I think following should work:

~~~java
    public void update(Graphics g, JComponent c) {
        if (shouldPaintPrompt((JTextComponent) c)) {
            if (!c.isOpaque()) {
                delegate.update(g, c);
            }
            super.update(g, c);
        } else {
            delegate.update(g, c);
        }
    }
~~~

Unfortunately, there is nothing I can do to fix this issue in FlatLaf...

**Comment by Bios-Marcel** [comment]
Thanks for looking into it again, I'll be closing the issue then.
