### ISSUE TITLE
Dark Themes Not Coloring Empty JTabbedPane Space Properly

### ISSUE THREAD

**Issue by andrewlalis** [JFormDesigner/FlatLaf#238]
![image](https://user-images.githubusercontent.com/9953867/104588758-25c2a480-5669-11eb-9c74-2a40f6ddc44d.png)
As you can see in the above image, the empty space not occupied by any tabs in this JTabbedPane still has its blinding white background color, which stands in stark contrast to the rest of the UI.

**Comment by Bios-Marcel** [comment]
Can you reproduce this in a standalone example?

**Comment by andrewlalis** [comment]
Ah nevermind I was calling `FlatDarculaLaf.install()` within my custom frame's constructor, thus after the parent JFrame had already been constructed.

**Comment by DevCharly** [comment]
This is expected behavior.
The JTabbedPane is non-opaque and does not fill the entire background.

Other Lafs (Windows Laf, Metal, Nimbus, JGoodies Looks etc) does it the same way.

Here is a screenshot of Windows Laf with custom background:
![image](https://user-images.githubusercontent.com/5604048/104594558-9bcb0980-5671-11eb-9583-d3138a666cf2.png)
