### ISSUE TITLE
Request: JBRWindowTopBorder Color consistent and immersive

### ISSUE THREAD

**Issue by rememberber** [JFormDesigner/FlatLaf#254]
To make FlatLaf looks consistent and immersive，like IntelliJ IDEA.
If possible, I would like to request  changing the default color in JBRWindowTopBorder  or adding an change option.

Thanks a lot!

![image](https://user-images.githubusercontent.com/4653893/107017311-eb68a500-67d9-11eb-986b-6262d82098e0.png)

![image](https://user-images.githubusercontent.com/4653893/107017593-4e5a3c00-67da-11eb-8d65-02d0d6f8fdbe.png)

**Comment by DevCharly** [comment]
Thanks for request.
At the moment I'm undecided whether this should be the default.
Especially when not using the JetBrains Runtime, all-gray dialogs are hard to recognize 
because they do not have drop shadow borders.
This will change soon when FlatLaf supports custom window decorations
with native Windows 10 drop shadows on all JREs. (I'm working on this)

If you want have this in your app now, do following:

Create a file `FlatLaf.properties` somewhere in the resources of your app (e.g. in package `com.myapp.resources`) with following content:
~~~
MenuBar.background = @background
~~~

Then tell FlatLaf in which package it can find the properties file with:
~~~java
FlatLaf.registerCustomDefaultsSource( "com.myapp.resources" );
~~~
**Note**: This must be done before setting the Laf!

See https://www.formdev.com/flatlaf/how-to-customize/#application_properties

**Comment by rememberber** [comment]
Thanks,got it!

**Comment by DevCharly** [comment]
@rememberber in FlatLaf 1.1 you can enable unified background with:
~~~java
UIManager.put( "TitlePane.unifiedBackground", true );
~~~

![image](https://user-images.githubusercontent.com/5604048/111073252-56df1a00-84de-11eb-9c57-2b720c07148d.png)

See PR #268
