### ISSUE TITLE
Table.cellMargins seems has no effect

### ISSUE THREAD

**Issue by JavaMaxim** [JFormDesigner/FlatLaf#258]
Hi,

I want to add more space and make table cell margins bigger, but using 

`UIManager.put( "Table.cellMargins", new InsetsUIResource( 8, 12, 8, 12 ) );` doesn't make the table cells bigger. I tried with JTable and JXTable.

Using `UIManager.put( "TableHeader.cellBorder", new FlatEmptyBorder( new InsetsUIResource( 8, 12, 8, 12 )  );` works for table header.

Also, `UIManager.put( "JXTable.rowHeight", 28 );` works, but `UIManager.put( "Table.rowHeight", 28 );` doesn't.

Please help.
flatlaf-1.0-rc2-2.jar

**Comment by DevCharly** [comment]
> UIManager.put( "Table.cellMargins", new InsetsUIResource( 8, 12, 8, 12 ) ); doesn't make the table cells bigger. 

`Table.cellMargins` is implemented in `FlatTableCellBorder` and is only used if the table cell renderer is a `DefaultTableCellRenderer`  (or a subclass), which is the default. If the renderer sets a own border, `Table.cellMargins` is also not used.

Is it possible that your table has a custom renderer that does not extend `DefaultTableCellRenderer`?

> .. doesn't make the table cells bigger

That is true This is standard `JTable` behavior (as far as I know).
But it should make the in-cell margins bigger. Does it?

`JTable.getCellRect()`, which is used to calculate table layout, uses `JTable.getRowHeight(int row)` to get the cell height. The renderer is not considered.

To make rows bigger, you have to also invoke `JTable.setRowHeight(int rowHeight)` or `JTable.setRowHeight(int row, int rowHeight)`.

> Also, UIManager.put( "JXTable.rowHeight", 28 ); works, but UIManager.put( "Table.rowHeight", 28 ); doesn't

Hmm,works for me.
Is it possible that `JTable.setRowHeight(int rowHeight)` is invoked somewhere in your code for that table?

If yes, FlatLaf does not overwrite the row height because it uses `LookAndFeel.installProperty(...)`, which does not overwrite already set row height:

https://github.com/JFormDesigner/FlatLaf/blob/909258ba1421d2023aa3b433c8bbf148fd363705/flatlaf-core/src/main/java/com/formdev/flatlaf/ui/FlatTableUI.java#L125

I would suggest to set a breakpoint at `JTable.setRowHeight(int rowHeight)` a check who is calling it.

`JXTable.rowHeight` works always because `JXTable` simply invokes `JTable.setRowHeight()`.

**Comment by JavaMaxim** [comment]
> Is it possible that your table has a custom renderer that does not extend `DefaultTableCellRenderer`

Yes, I used the subclass of  `org.jdesktop.swingx.renderer.DefaultTableRenderer`. When I changed it worked! Thanks!
