### ISSUE TITLE
Question: Is smooth scrolling available out of the box?

### ISSUE THREAD

**Issue by Chris2011** [JFormDesigner/FlatLaf#27]
The headline says it all: Is there a smooth scrolling feature which comes with the FlatLaf out of the box? When I use NetBeans with a nb-darcula theme for example the scrolling jumps to a specific number of rows. It is fixed. This features was implemented into NetBeans (one specific LaF) out of the box. It would be nice, if the FlatLaF will have it, if not :)

Cheers

Chris

**Comment by DevCharly** [comment]
No, smooth scrolling is not (yet) available.

I'll have a look...

- https://issues.apache.org/jira/browse/NETBEANS-49
- https://github.com/apache/netbeans/pull/881
- http://mail.openjdk.java.net/pipermail/awt-dev/2017-January/012507.html

**Comment by Chris2011** [comment]
Thx for the info :)

**Comment by DevCharly** [comment]
implemented in 0.24
(coming to NetBeans soon with my next PR)

**Comment by Chris2011** [comment]
Awesome :). Thank U so much. Will like to test it out

**Comment by bobbylight** [comment]
I tried 0.25.1 out today, and smooth scrolling isn't working for me, though it does work in IntelliJ.  I see your implementation looks different than that used in IntelliJ.  For me, this part of the conditional is not being met, thus I'm falling back to regular scrolling:

```java
e.getPreciseWheelRotation() != e.getWheelRotation() )
```
Why is this particular condition there (or more generally, how is it derived from the other implementations linked here and elsewhere?  Is there some mouse/OS setting I need to enable somewhere?

Kudos on getting a feature like this into the LaF - it's little things like this that really help the fidelity of Swing applications.

**Comment by DevCharly** [comment]
> Why is this particular condition there

This conditions simply checks whether the mouse has a high-resolution wheel.
If not, regular scrolling is used.

FlatLaf (currently) supports "smooth scrolling" only with high-resolution wheels or trackpads.
Maybe "smooth scrolling" is the wrong term, but with high-resolution wheels or trackpads it seems to scroll smooth because many many wheel events are fired when you (slowly) rotate the wheel, which means many repaints...

IntelliJ on the other hand seems to have some smooth scrolling for non-high-resolution wheels too.

While scrolling in IntelliJ looks smooth even with non-high-resolution wheels, you can not scroll e.g. half a line when you rotate very slowly. It scrolls always 3 lines (on Windows), but does some repaints to make it feel smooth.

With a high-resolution wheel or trackpads you can scroll pixelwise...

>  Is there some mouse/OS setting I need to enable somewhere?

Good question. I don't know.
But it seems that on Windows this is a OS/driver problem.
I have a mouse that supports high-resolution on macOS, but not on Windows.
Maybe smooth scrolling has to be enabled somewhere in Windows? Or a special mouse driver is needed?

**Comment by bobbylight** [comment]
Thanks.  I looked around and couldn't figure out to enable smooth/enhanced scrolling with my mouse.  Just wondering if you were aware of some Windows setting that worked for all/most users.

**Comment by DevCharly** [comment]
> Just wondering if you were aware of some Windows setting that worked for all/most users

No, sorry.

Maybe it is necessary to install additional software from the mouse vendor?
