### ISSUE TITLE
Components are very small

### ISSUE THREAD

**Issue by AlexAzarXYZ** [JFormDesigner/FlatLaf#281]
The components looks way smaller than on the demo. For example the title Bar. Also when sliding the app to the border it doesnt auto resize it.
![dmo](https://user-images.githubusercontent.com/79083143/112305938-2b56ef00-8c97-11eb-879b-7966f963eccc.PNG)
![ntb](https://user-images.githubusercontent.com/79083143/112305943-2bef8580-8c97-11eb-8fd2-85112304b40a.PNG)

**Comment by AlexAzarXYZ** [comment]
Resolved. System.setProperty( "flatlaf.uiScale", "2x" );
I use java 8, so There is no auto resizing based on the DPI.

**Comment by dinix2008** [comment]
@DevCharly, hello!
Perhaps for Java 8 it is worth changing the code of the UIScale # getSystemScaleFactor method, for example
```
public static double getSystemScaleFactor(GraphicsConfiguration gc) {
        if (isSystemScalingEnabled() && gc != null) {
            if (!SystemInfo.isJava_9_orLater) {
                try {
                    return (double) gc.getDevice().getClass().getField("scale").get(gc.getDevice());
                } catch (Exception e) {
                    return 1;
                }
            } else {
                return gc.getDefaultTransform().getScaleX();
            }
        }
        return 1;
    }
```

**Comment by DevCharly** [comment]
> Resolved. System.setProperty( "flatlaf.uiScale", "2x" );

This should be usually not necessary on Windows.
The font used in FlatLaf should be the same as used in Windows Explorer. 
And FlatLaf components are scaled if font is larger than default size (12pt on Windows).

> I use java 8, so There is no auto resizing based on the DPI.

But there is auto resizing based on Windows 10 scaling factor/font size.
FlatLaf Demo in first screenshot is scaled at 125% because font size is 15.

**Comment by DevCharly** [comment]
@dinix2008 hmm, can't find a field `scale` in Java 8 class `GraphicsDevice` or subclasses (on Windows). Where did you see this field?

**Comment by dinix2008** [comment]
@DevCharly, I used similar code on MacOS + Java 8. The scale field is in sun.awt.CGraphicsDevice.
<img width="927" alt="Снимок экрана 2021-03-24 в 16 15 24" src="https://user-images.githubusercontent.com/1597289/112316580-49831600-8cbc-11eb-80c2-1169ec1d94fd.png">

**Comment by DevCharly** [comment]
Ah, macOS. 

But reading field `scale` would not change anything in `UIScale.getSystemScaleFactor()`, because the current code
`gc.getDefaultTransform().getScaleX()`
actually does read this field. See implementation of `CGraphicsContext.getDefaultTransform()`:

~~~java
public AffineTransform getDefaultTransform() {
    double scaleFactor = device.getScaleFactor();     //  <--- this returns field `scale`
    return AffineTransform.getScaleInstance(scaleFactor, scaleFactor);
}
~~~

https://github.com/openjdk/jdk/blob/bc91596ca108ed366c35027cb01417d93543a1e0/src/java.desktop/macosx/classes/sun/awt/CGraphicsConfig.java#L62-L65

The reason that `UIScale.getSystemScaleFactor()` still returns `1` on Retina displays and Java 8 is that `isSystemScalingEnabled()` returns `false` for Java 8. Maybe `isSystemScalingEnabled()` should always return `true` on macOS...

**Comment by dinix2008** [comment]
@DevCharly, clear. I used this knowledge in another scenario, when I needed to draw icons in HiDPI. Thanks for the clarification
