### ISSUE TITLE
MenuItem left padding

### ISSUE THREAD

**Issue by DevCharly** [JFormDesigner/FlatLaf#3]
Left padding of menu items is inconsistent:

![image](https://user-images.githubusercontent.com/5604048/66033119-f1c08000-e506-11e9-9e8a-12d9c1eb2ea0.png)

**Comment by MioBlanco** [comment]
This only appears if you add a menu item **with** an icon and a checkBoxMenuItem in the same menu. The menu will always draw the checkIcon to the left of the default icons, so you have room for both checkIcon and a normal icon.
This can also be seen in the metal Look and Feel, because the same BasicMenuItemUI is used here. Here a screenshot 
![K5yPdswgdl](https://user-images.githubusercontent.com/56546322/79758037-2407c280-831d-11ea-9b4e-81f6cac437ae.png)


There are two solutions for this. One of them is you use the logic of the Windows Look and Feel, it handles the case like this:
CheckBox with icon: 
![ao4Ub0UiwR](https://user-images.githubusercontent.com/56546322/79758156-51547080-831d-11ea-86da-7f3c77a31987.gif)

CheckBox without icon: 
![x3prRdhDGu](https://user-images.githubusercontent.com/56546322/79758191-5ca79c00-831d-11ea-98f3-22c7c1193f35.gif)

The other possibility is that the CheckBoxMenuItemUI behaves in the same way as the normal MenuItemUI, with the difference that when selected the CheckBoxMenuItemUI shows the CheckIcon as the normal icon and when deselected, it shows a null icon instead. With the second variant it is no longer possible to use the CheckBox and normal icon.

**Comment by DevCharly** [comment]
@MioBlanco thanks for pointing out the possibilities.

The idea is it to have a stable left padding that is always the same even if there are no icons and no check/radio items. The padding should be not too large (room for icon and checkbox) because this looks ugly.

The solution used in the Windows LaF would be optimal, but the second solution would be also good IMO.

**Comment by DevCharly** [comment]
I've implemented a new menu item renderer in branch [menu-layout](https://github.com/JFormDesigner/FlatLaf/tree/menu-layout).

It uses currently the second variant described above by @MioBlanco 
The first variant is under development...

**Comment by DevCharly** [comment]
@MioBlanco first variant is now implemented in master branch

The accelerators are now right-aligned (as in Windows and macOS).
There is now a larger gap between the text and the accelerator.
The text and accelerator are no longer layouted in "columns", which makes menu width smaller.

![image](https://user-images.githubusercontent.com/5604048/80595501-22c54c80-8a25-11ea-9fcc-678608eb8ec8.png)

Also a new menu selection style is now available:

![image](https://user-images.githubusercontent.com/5604048/80596126-23121780-8a26-11ea-9a7c-023a910ba046.png)

Can be enabled with:

~~~java
UIManager.put( "MenuItem.selectionType", "underline" );
~~~
