### ISSUE TITLE
Color of a Button

### ISSUE THREAD

**Issue by martinm1000** [JFormDesigner/FlatLaf#30]
Hi ! I'm having difficulties with getting a colored background for a JButton or a JToggleButton depending on its state (red/green). I also just saw that version 0.22 changed this a little, but I feel we might need a way to specify a background color. I've tried many different combinations of opaque/etc but it seems hard. What do you think ?

**Comment by DevCharly** [comment]
A button has many states (**normal**, **hover**, **pressed**, **focused**, **default**) and each state has its own background colors. 

When the button is in **normal** state, `button.setBackground(Color.green)` works fine:
![image](https://user-images.githubusercontent.com/5604048/71108288-1271ab00-21c3-11ea-848b-6b0260aec024.png)

**Hover** and **pressed** states work also because there color is computed based on background color.

You can avoid that the button becomes the **default** state with `button.setDefaultCapable(false)`.
BTW what's changed in 0.22 is that "Button.defaultButtonFollowsFocus" is now enabled by default on Windows, which makes each button the default button when it is focused.

Remains the problem with the **focused** state, which you can avoid with `button.setFocusable(false)`

Then you have an always colored button.

**Comment by martinm1000** [comment]
Thank you, the default capable to false was the solution !
