### ISSUE TITLE
Incorrect insets

### ISSUE THREAD

**Issue by morvael** [JFormDesigner/FlatLaf#308]
JFrame with FlatDarkLaf returns insets of 0,8,8,8 disregarding the title bar height. Nimbus in the same setup returns 31,8,8,8. The extra 8s are another problem, but why is Flat forgetting the titlebar?

**Comment by DevCharly** [comment]
The insets are **correct** (on Windows 10) because if FlatLaf native window decorations are enabled (the default), then FlatLaf hides the Windows 10 system title bar and paints it itself (in dark 😉 ). The extra 8s are added by Windows 10 for the drop shadow.

If you use the JFrame insets to compute coordinates for content pane, then better work with `JFrame.getRootPane().getContentPane()`.

The assumption that the contentPane always has the same size as the JFrame`s client area is wrong. If the JFrame has a menubar, it is also smaller in all Lafs.

There are several `convert...` methods in class `SwingUtilities` to convert coordinates from one component to another one (e.g. from JFrame to contentPane).

Method `contentPane.getLocationOnScreen()` may be also useful if you work with screen coordinates.

If you've added an mouse listener to the JFrame, then consider adding the mouse listener to the contentPane instead.
Then you have mouse coordinates for contentPane.

**Comment by morvael** [comment]
Yeah, I need to calculate size of the area available for my panel knowing the external size of the frame. I don't know what the Shadow insets are for, they do nothing, and are just wasted space.

**Comment by DevCharly** [comment]
In Windows, the real window size is larger than the visible window.

The red rectangle in this screenshot indicates the real window size:
![image](https://user-images.githubusercontent.com/5604048/115111077-d1d49e00-9f7e-11eb-84bf-9f87a54b3dbb.png)

BTW if you like to have standard Windows 10 title bar, you can disable FlatLaf native window decorations.
See: https://github.com/JFormDesigner/FlatLaf/pull/267
