### ISSUE TITLE
L&F Default Font

### ISSUE THREAD

**Issue by kingthorin** [JFormDesigner/FlatLaf#312]
What's the "proper" way to override FlatLaf's default font(s)? 
We currently do this: UIManager.getLookAndFeelDefaults().put("defaultFont", font); but it doesn't seem to work.

It does work with Nimbus, but doesn't seem to with FLatLaf.

That's with FlatLaf 1.1.2 in my testing I was using Adopt OpenJDK 11.0.6+10 (though I don't think that impacts things, but more detail is usually a good thing :wink: )

**Comment by DevCharly** [comment]
~~~java
UIManager.getLookAndFeelDefaults().put("defaultFont", font);
~~~
or
~~~java
UIManager.put("defaultFont", font);
~~~
also works in FlatLaf if you update the UI with (after setting the font):
~~~java
FlatLaf.updateUI();
~~~
or with
~~~java
for( Window w : Window.getWindows() )
    SwingUtilities.updateComponentTreeUI( w );
~~~

The [FlatLaf Demo](https://github.com/JFormDesigner/FlatLaf#demo) uses this for the "Font" menu:

https://github.com/JFormDesigner/FlatLaf/blob/f58780d36b245fa01b20feb1bffd7cd215e491c2/flatlaf-demo/src/main/java/com/formdev/flatlaf/demo/DemoFrame.java#L186-L190

Using `StyleContext.getDefaultStyleContext().getFont(family,style,size)` instead of `new Font(family,style,size)` enables displaying any characters, even those that are not part of that font. E.g. Chinese characters.

> It does work with Nimbus, ...

Really, Nimbus updates existing components? Without updateUI()?

In my test this did not work very well. Existing components were not updated. And even newly created dialogs used the new font only for some components (JTextField, JComboBox, ...), but not for JLabel or JButton...

**Comment by kingthorin** [comment]
To clarify the nimbus point that’s after stopping the app and relaunching. But even doing that FlatLaf didn’t seem to be using the font.

I’ll check further, it might be an order of operations issue. Perhaps the L&F is being set then the font without doing an update or something.

Thanks for the tips.

**Comment by kingthorin** [comment]
It appears this might be related to a Syntax highlighting component, not FlatLaf at all. I'm going to close for now and will re-open if I have further questions.

Thanks very much for your support @DevCharly ❕
