### ISSUE TITLE
JFrame and JInternalFrame SVG icons rendered in low resolution

### ISSUE THREAD

**Issue by electriq** [JFormDesigner/FlatLaf#323]
Hello!

I use ``FlatSVGIcon`` to set in ``JInternalFrame.setFrameIcon()`` and custom ``MultiResolutionImage`` based on ``FlatSVGIcon`` for ``JFrame.setIconImage()`` (unfortunately JFrame does not take Icon, only Image). I found that in v. 1.1.2 in our deployment build the icons of the frame and internal frame in hi-res mode (Windows/Mac OS retina) are rendered in low resolution (smooth and pixelized). But icons looks OK if I run the app from the IDE. All other icons on JButtons, in menus, etc. are OK. I don't understand what is the difference between running from the IDE and the deployment build, the only thing that can matter is that our code is obfuscated (ProGuard). The library code is not obfuscated, but we pack all code in a single jar.

I'm sorry for such uncertain description, I will continue to investigate the issue to find some minimal (un-)working prototype to work with. There was no such issue in v. 0.46 that we used before.

I found the issue with JFrame icon first and tried to fix it with our implementation of ``MultiResolutionImage`` based on ``FlatSVGIcon``. I experimentally fixed the issue by returning a default size image in ``getBaseImage()`` instead of 128x128 image that this method returned before. Overall, when running from IDE (125% size in Windows), only ``getResolutionVariants()`` and two ``getResolutionVariant()`` are invoked for 20x20 and 40x40 (frame icon and taskbar icon, I suppose). But in deployment build also ``getBaseImage()`` is invoked. I don't understand what's the difference and will update the issue with new information.

**Comment by DevCharly** [comment]
For `JFrame.setIconImage()` you could use `FlatSVGUtils.createWindowIconImages()`, as used in the FlatLaf Demo:
https://github.com/JFormDesigner/FlatLaf/blob/9edaf5892949523096a1270e45b16b06e4fb4d68/flatlaf-demo/src/main/java/com/formdev/flatlaf/demo/DemoFrame.java#L64

Don't know whether Java multi-resolution images work for window title bars,
especially when FlatLaf custom window decorations are not enabled or not available (Linux or macOS).

If FlatLaf custom window decorations are enabled, it would be optimal to paint SVG directly in window title bar,
but this not yet the case... will look into this...

>... but we pack all code in a single jar.

Make sure that `META-INF/versions` directory from `flatlaf.jar` is included
and the manifest contains `Multi-Release: true`.
If one is missing, you probably get low-res images if using FlatLaf `MultiResolutionImageSupport` class.

**Comment by DevCharly** [comment]
BTW there are some test icons, for various sizes in different colors, in FlatLaf repo:
https://github.com/JFormDesigner/FlatLaf/tree/main/flatlaf-testing/src/main/resources/com/formdev/flatlaf/testing
![image](https://user-images.githubusercontent.com/5604048/118033390-0ca4d880-b369-11eb-8379-d44c4dc26896.png)

When using these icons for `frame.setIconImages()` or for multi-resolution images, you can see immediately which resolutions was used for painting:

https://github.com/JFormDesigner/FlatLaf/blob/9edaf5892949523096a1270e45b16b06e4fb4d68/flatlaf-testing/src/main/java/com/formdev/flatlaf/testing/FlatWindowDecorationsTest.java#L42-L49
https://github.com/JFormDesigner/FlatLaf/blob/9edaf5892949523096a1270e45b16b06e4fb4d68/flatlaf-testing/src/main/java/com/formdev/flatlaf/testing/FlatWindowDecorationsTest.java#L52

**Comment by DevCharly** [comment]
> For JFrame.setIconImage() you could use FlatSVGUtils.createWindowIconImages() ...

To clarify: I meant method `Window.setIconImages​(List<? extends Image> icons)`,
which accepts a list of images. No need for a multi-resolution image here.

**Comment by electriq** [comment]
Hi Karl, thank you for quick and detailed reply!

> Make sure that `META-INF/versions` directory from `flatlaf.jar` is included
> and the manifest contains `Multi-Release: true`.
> If one is missing, you probably get low-res images if using FlatLaf `MultiResolutionImageSupport` class.

Yes, that was it. I didn't look into `flatlaf.jar` at all, thought that Maven makes all automatically...

> Don't know whether Java multi-resolution images work for window title bars,

It is used, I know it by listing the invoked methods of our `SVGMultiResolutionImage` class (when FlatLaf's Multi-release is properly set). For 125% scale `getResolutionVariant(20, 20)` and `getResolutionVariant(40, 40)` are invoked for JFrame icon.

> For `JFrame.setIconImage()` you could use `FlatSVGUtils.createWindowIconImages()`

Thank you for this tip. I have looked the code of `createWindowIconImages()` and I suggest to add more resolution variants, at least `20 px (16*1.25), 28 px (16*1.75), 30 px (24*1.25)`, etc.: these sizes are used for 125%, 175% scale of Windows OS. I personally prefer to leave (rely on) `getResolutionVariant()` of `MultiResolutionImage` because Windows allows setting of manual scale value, 120%, for example, and only 'true' vector image that can be rendered in really any resolution will look good. 125% scale is very common on 15" 1920x1080 laptops.

**Comment by DevCharly** [comment]
Aha, now I understand the advantage of using multi-resolution image for frame icon 😄 

Tried following in `FlatSVGUtils.createWindowIconImages()`:

~~~java
if( MultiResolutionImageSupport.isAvailable() ) {
    return Collections.singletonList( MultiResolutionImageSupport.create( 0,
        new Dimension[] {
            new Dimension( 16, 16 ),
        }, dim -> {
            System.out.println( "produce "+dim );
            return svg2image( diagram, dim.width, dim.height );
        } ) );
}
~~~
...creates images in following sizes (at 150%):
~~~
produce java.awt.Dimension[width=48,height=48]
produce java.awt.Dimension[width=24,height=24]
produce java.awt.Dimension[width=16,height=16]
~~~

That is great because it avoids creating unused images.
Unfortunately, if FlatLaf window decorations are enabled, the 16x16 image is always used.
Need to fix this...

> `30 px (24*1.25)`

Not sure about this. Where is this used?
Or did you mean `40 px (32*1.25)`?

**Comment by electriq** [comment]
> Unfortunately, if FlatLaf window decorations are enabled, the 16x16 image is always used.

Did you mean the embedded menu bar mode for JFrame? It takes 20x20 image, so it seems working.

> `30 px (24*1.25)`
> Not sure about this. Where is this used?
> Or did you mean `40 px (32*1.25)`?

It's for 24 px icons which are sometimes used (NetBeans IDE, for example have 24 px toolbar by default).

**Comment by DevCharly** [comment]
> Did you mean the embedded menu bar mode for JFrame? 

Yes.

> It takes 20x20 image (for 125%), so it seems working.

But only if 20x20 is in the list of resolution variants. My above code snippet has only 16x16.

I've now changed handling of multi-resolution images in `FlatTitlePaneIcon`.
It is now similar to `SunToolkit.getScaledIconImage()`.

Previously `MultiResolutionImage.getResolutionVariants()` was used to get all images variants and then the resulting list was queried for best matching size. This has the disadvantage that all the variant images needs to be created and only the (predefined) variant sizes are supported.

Now `MultiResolutionImage.getResolutionVariant(width, height)` is used to request a image for needed size.
This allows the multi-resolution image to create a image on demand for **any needed size** from SVG.
And only used images needs to be created.

https://github.com/JFormDesigner/FlatLaf/blob/8998371caea610ee8f931f4ad2191fe2913a5fe6/flatlaf-core/src/main/java/com/formdev/flatlaf/ui/FlatTitlePaneIcon.java#L46-L51

https://github.com/JFormDesigner/FlatLaf/blob/8998371caea610ee8f931f4ad2191fe2913a5fe6/flatlaf-extras/src/main/java/com/formdev/flatlaf/extras/FlatSVGUtils.java#L62-L80

BTW I've tested this also on macOS and Linux and it turns out that multi-resolution images are not supported for window icons on these platforms.
