### ISSUE TITLE
Add methods that take java.lang.Module as well as java.lang.ClassLoader for loading resources

### ISSUE THREAD

**Issue by gtimbo** [JFormDesigner/FlatLaf#325]
I have a (relatively low priority) request for better Java 9 JPMS support. There are currently a number of methods that load resources where you accept a `ClassLoader` as a parameter. For example, `FlatSVGIcon(String, ClassLoader)` and `FlatLaf.registerCustomDefaultsSource(String, ClassLoader)`. These are just the ones that I've used so far.

When using `ClassLoader` in conjunction with JPMS, the package in which the resource resides must be fully open, whereas using `Module` enables us to limit the visibility of the package.

It would be helpful to add specific JPMS support to these (and potentially other) classes, by adding variants that take a `Module`, and use that to load the resources.

**Comment by DevCharly** [comment]
Adding methods with `Module` parameter is a problem because this would break Java 8 compatibility.

In case of `FlatSVGIcon` it would be also necessary to change svgSalamander library to accept an `InputStream` for reading SVG.
Method `module.getResourceAsStream​(String name)`, which returns `InputStream`, is the only method I've found to access a resource in a module.

But maybe there is another possible solution using `URL` (at least for `FlatSVGIcon`).
Found out that following works without opening package `myicons` (in `module-info.java`):
~~~java
URL url = MyApp.class.getResource( "/myicons/error.png" );
Icon icon = new ImageIcon( url );
System.out.println( icon.getIconWidth() );
~~~

So I did a quick test and added constructor `FlatSVGIcon( URL url )`
and it seems to load the SVG without the need to open the package in module descriptor 😄

**Comment by gtimbo** [comment]
> Adding methods with `Module` parameter is a problem because this would break Java 8 compatibility.

Yep. I guess I was thinking more along the lines of using the multi-release jar functionality (which you're already using) to provide an alternative API for Java 9 and above (although, note that I actually have no idea if you can have different APIs for a class that appears in both sections of the jar). It would require some thinking about as they're not trivial classes. Hence I raised it more as an aid to thinking about how you might go about it in a future version.

Realistically, it's not that big a deal. It just feels like a nice-to-have.

> In case of `FlatSVGIcon` it would be also necessary to change svgSalamander library to accept an `InputStream` for reading SVG.
> Method `module.getResourceAsStream​(String name)`, which returns `InputStream`, is the only method I've found to access a resource in a module.

It looks like you can call `SVGUniverse.loadSVG(InputStream, String)`, which returns you a `URI` that can then be used in the call to `getDiagram(URI)`.

**Comment by DevCharly** [comment]
I've added a constructor to `FlatSVGIcon`, which allow loading SVG from `URL`.
This allows loading SVGs from packages that are not opened in `module-info.java`:

~~~java
new FlatSVGIcon( getClass().getResource( "/com/myapp/icons/myicon.svg" ) );
~~~

Have also added `FlatLaf.registerCustomDefaultsSource(URL packageUrl)`
that allows loading FlatLaf applications properties files from a package that is not opened in `module-info.java`.

~~~java
FlatLaf.registerCustomDefaultsSource( MyApp.class.getResource( "/com/myapp/themes/" )
~~~

When using own classes in FlatLaf applications properties it is still necessary to export them in  `module-info.java`. E.g.:

~~~
ButtonUI = com.myapp.MyButtonUI
Button.border = com.myapp.MyButtonBorder
~~~

Since the classes for the UI delegates (e.g. `MyButtonUI`) are loaded (via reflection) from `javax.swing.UIDefaults.getUI()`, I'm not sure whether it is even possible to use UI delegates without exporting their package in `module-info.java`...

So, I think that's all I can do at the moment for better JPMS support...
