### ISSUE TITLE
Table various UI issues

### ISSUE THREAD

**Issue by Chrriis** [JFormDesigner/FlatLaf#332]
Hi!

I see a certain number of odd behaviors related to tables.
![TableIssues1](https://user-images.githubusercontent.com/1174202/119653927-2e519580-be28-11eb-8f51-f7f141bb4d86.png)

- I think it is a bug that focus indication is visible for boolean column (it is not the case for other columns).
- Selection background stops 1px before the end of the row.
- It feels odd to miss the last separator line when the vertical scroll bar is showing: it is as if there is more content going under the scroll bar.
- It feels odd to have the resize cursor on the header of the end of the last column.

Test code:
```Java
public static void main(String[] args) throws Exception {
	UIManager.setLookAndFeel(new FlatLightLaf());
	// UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
	UIManager.put("Table.showVerticalLines", Boolean.TRUE);
	UIManager.put("Table.showHorizontalLines", Boolean.TRUE);
	UIManager.put("Table.intercellSpacing", new Dimension(1, 1));
	UIManager.put("Table.gridColor", new Color(0xd9d9d9));
	JFrame frame = new JFrame();
	frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
	JPanel centerPane = new JPanel(new GridBagLayout());
	centerPane.setBorder(BorderFactory.createEmptyBorder(10, 10, 10, 10));
	Object[][] data = new Object[][] { { "Cell 1_1", Boolean.FALSE, "Cell 1_3" }, { "Cell 2_1", Boolean.TRUE, "Cell 2_3" }, { "Cell 3_1", Boolean.TRUE, "Cell 3_3" } };
	String[] titles = new String[] { "Column1", "Column2", "Column3" };
	AbstractTableModel tableModel = new AbstractTableModel() {
		@Override
		public Object getValueAt(int rowIndex, int columnIndex) {
			return data[rowIndex][columnIndex];
		}
		@Override
		public int getRowCount() {
			return data.length;
		}
		@Override
		public int getColumnCount() {
			return titles.length;
		}
		@Override
		public Class<?> getColumnClass(int columnIndex) {
			return columnIndex == 1 ? Boolean.class : String.class;
		}
	};
	JTable table1 = new JTable(tableModel);
	centerPane.add(new JScrollPane(table1), new GridBagConstraints(0, 0, 1, 1, 1, 1, GridBagConstraints.WEST, GridBagConstraints.BOTH, new Insets(0, 0, 2, 0), 0, 0));
	JTable table2 = new JTable(tableModel);
	JScrollPane scrollPane2 = new JScrollPane(table2);
	scrollPane2.setMinimumSize(new Dimension(60, 60));
	centerPane.add(scrollPane2, new GridBagConstraints(0, 1, 1, 1, 1, 1, GridBagConstraints.WEST, GridBagConstraints.HORIZONTAL, new Insets(0, 0, 0, 0), 0, 0));
	centerPane.add(new JTextField(14), new GridBagConstraints(0, 2, 1, 1, 0, 0, GridBagConstraints.WEST, GridBagConstraints.HORIZONTAL, new Insets(0, 0, 0, 0), 0, 0));
	frame.getContentPane().add(centerPane);
	frame.setSize(400, 300);
	frame.setVisible(true);
}
```

Another problem related to the last vertical separator not being painted is when we create advanced tables using a composition of tables. Here is an example taken from a real-world application with FlatLaf, where the first column is a separate table acting like a row header, the second column is a "frozen" (tree) table so that only the rest (a third table) can scroll. At every end of table the separator is missing although it should not in this case:
![TableIssues2](https://user-images.githubusercontent.com/1174202/119654732-0a428400-be29-11eb-8440-93dc84c4922f.png)

Is there a global property to paint the last vertical separator? Is there a per-table property to activate/deactivate the painting of the last separator?

And once again, thanks a lot for the great work! 😉

**Comment by DevCharly** [comment]
> I think it is a bug that focus indication is visible for boolean column (it is not the case for other columns).

Yes. It is actually a Swing bug in class `JTable.BooleanRenderer`, which does not use `Table.focusSelectedCellHighlightBorder` for selected cells (as `DefaultTableCellRenderer` does). Instead `Table.focusCellHighlightBorder` is used.

I tried to fix this in cell border [FlatTableCellBorder.Focused](https://github.com/JFormDesigner/FlatLaf/blob/78a9cc1d0c150b29f1950bfd9e6d7ebac96bcf90/flatlaf-core/src/main/java/com/formdev/flatlaf/ui/FlatTableCellBorder.java#L61-L64) (as done in class [FlatTableCellBorder.Selected](https://github.com/JFormDesigner/FlatLaf/blob/78a9cc1d0c150b29f1950bfd9e6d7ebac96bcf90/flatlaf-core/src/main/java/com/formdev/flatlaf/ui/FlatTableCellBorder.java#L76-L81)), but this does not work because the border does not know what cell it is painting and can not determine whether the cell is selected.


> Selection background stops 1px before the end of the row.

Yes, because the last vertical separator line is hidden 😉 
It would be necessary to make the cells in last column wider.
Can't fix this (at the moment) because table cell painting methods are all private.
A fix requires re-implementation of table cell painting in FlatLaf, which is a larger task.
(copying source code from `BasicTableUI` is not allowed because of incompatible licenses)


> It feels odd to miss the last separator line when the vertical scroll bar is showing: it is as if there is more content going under the scroll bar.

but then is looks odd when there is no scroll bar:

![image](https://user-images.githubusercontent.com/5604048/132095460-6a49b675-28ae-49f5-8a11-a280ab68703e.png)

A workaround would be to add a border to the vertical scrollbar. E.g.:
~~~java
scrollPane2.getVerticalScrollBar().setBorder( new MatteBorder( 0, 1, 0, 0, UIManager.getColor( "Table.gridColor" ) ) );
~~~

> It feels odd to have the resize cursor on the header of the end of the last column.

Actually a bug in Swing, but I found a workaround and fixed it in commit d508f339c1ec7424be5ea369089990fadea88698


> Another problem related to the last vertical separator not being painted ...

Fixed in commit fa194ec258d19530cc0e1ff0ffc4c3b7eda956bc

> Is there a global property to paint the last vertical separator? Is there a per-table property to activate/deactivate the painting of the last separator?



Yes, since commit 824db2e3bdb586dfea959d5e6101616ce9a918b3 you can use:
~~~java
UIManager.put( "Table.showLastVerticalLine", true );
UIManager.put( "TableHeader.showLastVerticalLine", true );
~~~
