### ISSUE TITLE
All text rendered in Bold on some Windows platforms

### ISSUE THREAD

**Issue by ptorngren** [JFormDesigner/FlatLaf#337]
For some reason, all text is rendered **bold** in some contexts; the same binary distribution runs fine on some platforms but renders all text as bold on others, and the same application also runs fine from inside IntelliJ but fails when launched from the externally compiled jar (on the same computer). 

Have not been able to find any common denominator except that it seems to be worse with some fonts than others (Arial seems more stable than Segoe UI). Changing Java compiler or runtime JRE (Open JDK 8/11) does not have any effect, and when comparing internal and external launch, I cannot find any relevant settings that differ (System properties, JVM directives, UI Manager defaults, classpath ...). The only thing that seems to stand out is that the problem seems worse when using the default system font and better when built and launched from inside IntelliJ, but I cannot figure out why.

Some screenshots from our font settings dialog, where the tree on the left should not be rendered in bold:

**Correct (internal launch):**
![image](https://user-images.githubusercontent.com/38153291/121023370-8337c900-c7a3-11eb-9aba-9d41cd19e98b.png)

**Incorrect (external launch):**
![image](https://user-images.githubusercontent.com/38153291/121023758-df9ae880-c7a3-11eb-9bd8-9593ac8bde12.png)

**Correct (external launch with different font):**
Note: the listing in the tree is correct, but labels are still bold (they are not controlled by this font setting)
![image](https://user-images.githubusercontent.com/38153291/121024016-1b35b280-c7a4-11eb-9b61-701c0e7300eb.png)

**Comment by DevCharly** [comment]
Strange...
I can reproduce it with DbVisualizer 12.0.7.

After some testing I found out that it has something to do with the Metal Laf that is used at DbVisualizer startup for the License dialog and for the light/dark chooser dialog.

Even if those dialogs are not shown, the Metal Laf is initialized because some DbVisualizer code invokes `UIManager.getColor()` before FlatLaf is setup. This automatically activates Metal Laf. You can easy find it if you set a breakpoint at `UIManager.setLookAndFeel()`:

~~~
UIManager.setLookAndFeel(LookAndFeel) line: not available	
UIManager.setLookAndFeel(String) line: not available	
UIManager.initializeDefaultLAF(Properties) line: not available	
UIManager.initialize() line: not available	
UIManager.maybeInitialize() line: not available	
UIManager.getDefaults() line: not available	
UIManager.getColor(Object) line: not available	
c(g<COLUMNSET,ROW>).<init>(COLUMNSET) line: 1897	
c(v<COLUMNSET,ROW>).<init>(COLUMNSET) line: 3097	
c(j<ROW>).<init>(l<b>) line: 3314	
c(g).<init>(l, c) line: 1388	
c.<init>() line: 337	
b.<init>() line: 907	
p.e() line: 1029	
n.k() line: 1075	
q.<init>() line: 998	
h.<clinit>() line: 3102	
DbVisualizerGUI(d).initLogging(int) line: 3090	
DbVisualizerGUI(e).initialize() line: 449	
DbVisualizerGUI.b(DbVisualizerGUI) line: 1797	
DbVisualizerGUI.initialize() line: 3562	
DbVisualizerGUI$1.run() line: 1027	
~~~

It is also reproducable with the FlatLaf Demo:
1. start FlatLaf Demo
2. switch to Metal Laf with `F12` key
3. quit FlatLaf Demo
4. start FlatLaf Demo (shows Metal Laf)
5. switch to FlatLaf with `F1` key --> all in bold

To fix this in DbVisualizer you could setup FlatLaf very early to avoid that Metal Laf gets activated.

Since FlatLaf supports Laf switching, you can e.g. start always with the light theme and later switch to dark if necessary.

Regarding the "Select theme" dialog: It would be nice to immediately switch to light/dark theme when the user clicks one of the light/dark radio buttons. Then the user can immedately see what it will look like. BTW for usability, I would recommend to stop the 10 second timer when the user clicks some radio/check button in that dialog.

~~~java
if( lightRadioButton.isSelected() )
    FlatLightLaf.setup();
else
    FlatDarkLaf.setup();

FlatLaf.updateUI();
~~~

**Comment by DevCharly** [comment]
For some reason, Metal changes something in Java's font file lookup.
The `java.awt.Font` object is not bold, but the internally used `sun.font.TrueTypeFont` object is bold:

![grafik](https://user-images.githubusercontent.com/5604048/121182931-d4a78d00-c863-11eb-9a71-77b964fae310.png)

**Comment by ptorngren** [comment]
Thanks a lot! Will look into this asap!

**Comment by rogerbj** [comment]
@DevCharly, Thanks for your detailed analyze. Even though running setLookAndFeel() as the very first call to initiate FlatLaf,  in some Windows environments fonts are still bold. Seems to be something in the user's Windows config/registry that causes it to happen. My colleague gets all bold while I don't. We use the very same app setup... Very strange.

**Comment by ptorngren** [comment]
Having looked into this a bit more, it seems that the problem is related to the default font reported by Windows, ie **Segoe UI**.

As a quick test, I override the font setting that is done in `com.formdev.flatlaf.FlatLaf.initFonts(UIDefaults)`; instead of using the font returned by  `(Font)Toolkit.getDefaultToolkit().getDesktopProperty("win.messagebox.font")` in this method, I call         `UIManager.put("defaultFont", defaultFont)` and set another font (after calling `UIManager.setLookAndFeel(String)`). This yields the desired results; text is bold/plain/italic as expected (it should be noted that I don't call `com.formdev.flatlaf.FlatLaf.createCompositeFont(...)` the way the `initFonts()` method does).

**The prime suspect is the Segoe UI font.**

I have no idea why this would fail, but having experimented with different fonts, it seems that most of the other fonts work fine (Arial, Dialog, Calibri, to name a few). When debug logging and inspecting the actual fonts in use by the application components, they now (after avoiding the Metal LAF) report the correct font (Segoe UI, not Segoe UI Bold) - but the text is still rendered bold. I've also tried to explicitly set the Segoe UI font in an attempt to eliminate any setup problems, but this has no effect; text is still bold when using **Segoe UI** but correct when using other fonts.

Also: having studied the FlatLaf customizing page (https://www.formdev.com/flatlaf/customizing/), I don't see any advice on how to override the default font. Is there a proper/better way to do this?

**Comment by DevCharly** [comment]
Have not yet found the reason why Segoe UI font is bold on some Windows 10 systems, but found out how to avoid it:
do not invoke `GraphicsEnvironment.getAvailableFontFamilyNames()` or `getAllFonts()` before `FlatLightLaf.setup()`.

Here is a super simple test case to reproduce it:
~~~java
import java.awt.GraphicsEnvironment;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import com.formdev.flatlaf.FlatLightLaf;

public class SegoeUIBoldTest
{
    public static void main( String[] args ) {
        SwingUtilities.invokeLater( () -> {
            GraphicsEnvironment.getLocalGraphicsEnvironment().getAvailableFontFamilyNames();
//          GraphicsEnvironment.getLocalGraphicsEnvironment().getAllFonts();
            FlatLightLaf.setup();
            JOptionPane.showMessageDialog( null, "test" );
        } );
    }
}
~~~

On some WIndows systems the dialog is in bold.
When removing invocation of `getAvailableFontFamilyNames()` then it is not bold.

This method is also used in FlatLaf Demo:
https://github.com/JFormDesigner/FlatLaf/blob/ff9ef21f67dfa96abf97ad27c3c1d1f57798c083/flatlaf-demo/src/main/java/com/formdev/flatlaf/demo/DemoFrame.java#L56-L57

This explains why I was able to reproduce the issue with the FlatLaf Demo, but not with other test apps.

But the question is still, why does it not work on some systems...

**Comment by ptorngren** [comment]
Good news, we will look into this! I am somewhat comforted to realize that I'm not the only one bewildered by this seemingly random behavior ;-)

**Comment by ptorngren** [comment]
Yes, this does indeed seem to do the trick. THANK YOU! 🥇 

Closing this as our issue is resolved, but would be very interested in understanding why this happens. Seems like a bug in the Windows JRE?

**Comment by ptorngren** [comment]
PS: It might be worth mentioning that this doesn't affect only **Segoe UI**, some other fonts are also affected. Have not tested all ;-) but noticed that **Tahoma** seems to behave the same way.
