### ISSUE TITLE
Dark theme: Flickering when opening frames and dialogs

### ISSUE THREAD

**Issue by mf-arb** [JFormDesigner/FlatLaf#339]
When opening frames and dialogs in dark mode, the dialog briefly flashes white before being drawn in dark gray. This short bright flickering is very annoying and does not always appear. The problem also occurs in the demo application when opening the 'Options/Show UI defaults inspector' dialog (not always but sometimes).

**Comment by LG987234122** [comment]
I see this same effect also. It's more noticeable when running under Webswing.

**Comment by DevCharly** [comment]
I've seen this too, sometimes, but don't think that I can do something here (in Java code). The background color of the `java.awt.Window` is already dark. Not sure whether Swing or Windows 10 fills the window with a light color. Have to dig into Swing/AWT C++ code...

If the FlatLaf native library is used, there is maybe a possibility to improve this. Will try...

Regarding Webswing: don't think that something can be done in FlatLaf here. But maybe you can use some CSS to change the background color of the Webswing browser window. Please contact Webswing developers.

**Comment by DevCharly** [comment]
Fixed in main branch for Windows 10 when using FlatLaf native library (the default)

This was easy to reproduce when the screen content is dark and opening a large dark window.
Then the new window was white for a short moment before its actual content was shown.

@mf-arb on what operating system did you see this?

CC @ingokegel
