### ISSUE TITLE
Horizontal grid lines in JTable disappear if cell has background

### ISSUE THREAD

**Issue by psembass** [JFormDesigner/FlatLaf#348]
![image](https://user-images.githubusercontent.com/18038056/124608730-a378a780-de77-11eb-882c-09b00efda4bf.png)

**Comment by DevCharly** [comment]
The problem is that the background of the cell paints over the grid lines
because the intercell spacing is `0, 0` in FlatLaf. Other Lafs use intercell spacing `1, 1`.

To fix this, change intercell spacing to `1, 1` for this table with:
~~~java
table.setIntercellSpacing( new Dimension( 1, 1 ) );
~~~

Or for all tables with:
~~~java
UIManager.put( "Table.intercellSpacing", new Dimension( 1, 1 ) );
~~~

Intercell spacing is zero in FlatLaf because grid lines are hidden by default in FlatLaf.

Intercell spacing affects selection painting:

![image](https://user-images.githubusercontent.com/5604048/115465190-7f210d80-a22e-11eb-8041-43f61bd15e24.png)

With zero intercell spacing:

![image](https://user-images.githubusercontent.com/5604048/115465195-82b49480-a22e-11eb-87a3-0f2efcb81f6d.png)

**Comment by psembass** [comment]
Thank you! Maybe you can add this to the Customize page in documentation?
