### ISSUE TITLE
JComboBox cell editor height problem in JTable

### ISSUE THREAD

**Issue by tristanzhou** [JFormDesigner/FlatLaf#352]
Hi,
I found that the table row height for the JComboBox cell editor seems not enough for displaying the whole text. It works in some of the fonts and sizes. Does FlatLaf support automatic updating table row height in this case? Thanks.

![jcombobox-cell-editor-issue-windows](https://user-images.githubusercontent.com/5662534/125227455-0d38fb80-e327-11eb-9bee-2abec1a21207.png)

![jcombobox-cell-editor-height-issue](https://user-images.githubusercontent.com/5662534/125227178-8126d400-e326-11eb-9a93-c18265b8540a.png)

**Comment by Bios-Marcel** [comment]
You could probably write a ethod that iterates over all editors and calls `getPreferredSize()` once in order to find out the optimal size. I think it'd be very weird for flatlaf to do this automatically.

**Comment by DevCharly** [comment]
In Swing the `JTable` row height is not computed based on the cell renderers/editors. It is set via `JTable.setRowHeight()`.
This is different to `JList` and `JTree`, which use the preferred size of the renderers to compute row heights.

FlatLaf computes a "user scale factor" based on the application font and then scales the default table row height of `20` using this factor.

The base font size on Linux is 15, so the "user scale factor" for "Comic Sans MS 20" should be 1.25x on Linux.
But your screenshot shows "no scaling" (in bottom bar).

There seems to be a problem in FlatLaf Demo because when I first set font size to 20 (in "Font" menu) and then change font family to "Comic Sans MS", the bottom bar shows "no scaling" (as in your screenshots). But when I first set the font family to "Comic Sans MS" and then the font size to 20, the bottom bar shows "user scale factor 1.25" (and the table rows are higher).
