### ISSUE TITLE
JMenuBar not compatible with Java 8u51

### ISSUE THREAD

**Issue by CrackheadV** [JFormDesigner/FlatLaf#360]
JMenuBar in Java (version 8u51) is not displayed in the title bar.
For example: Try launching the flatlaf-demo with Java 8u51.

**Comment by DevCharly** [comment]
The reason is that this very very old Java version (from 2015) does not know Windows 10.
System property `os.name` reports `Windows 8.1` and `os.version` is `6.3`.
Current Java versions report `Windows 10` and `10.0`.

Even if I change the check in FlatLaf to enable embedded menu bar with Java 8u51,
it does not work. The demo frame is shown, but it hangs...

Please use a newer Java version.
