### ISSUE TITLE
JComboBox with custom renderer will not render correctly the selected value (arrow to big)

### ISSUE THREAD

**Issue by sbodmer** [JFormDesigner/FlatLaf#361]
When I define a custom renderer on a JComboBox, the selected value is displayed (I think) with the custom renderer, but the arrow button takes all the space.
![FlatCombobox](https://user-images.githubusercontent.com/18146968/127017075-42258ee9-6277-40ce-b055-7dbefdb924ce.png)
Using a common Laf (ex: Nimbus), the arrow is small and the image is displayed in full.

**Comment by DevCharly** [comment]
Thx. Fixed in main branch.

The width of the arrow button is now limited the height of a raw combobox/spinner,
which keeps it square in normal cases, but avoids that it becomes too wide.

![image](https://user-images.githubusercontent.com/5604048/127872615-c82a36b3-3b94-4908-b2e4-e6ab16ea4c18.png)
(this image shows comboboxes and spinners that are taller than normal)
