### ISSUE TITLE
Table grid is not drawn if cell renderer paints its own background

### ISSUE THREAD

**Issue by hubersn** [JFormDesigner/FlatLaf#381]
I am using FlatLaf 1.5 with a slightly changed FlatLight theme (switching on horizontal and vertical table grid by default) on Windows 10.

If I have a JTable with a custom CellRenderer which sets the component to opaque and a background colour to non-WHITE, the table's grid is not visible at all. If using a different L&F like Windows or Metal, it works. For non-opaque renderers, the grid is visible. This looks extremely strange when mixing opaque and non-opaque renderers in each row.

As a workaround, if I set the intercell spacing to 1, the grid suddenly appears.

**Comment by DevCharly** [comment]
That is normal behavior.

This is because the table (in class `BasicTableUI`) **first paints the grid lines** and **then the cells**.
Not sure why, but maybe to allow custom cell renderers to paint over the grid and "join" cells.

In FlatLaf, by default, the table grid lines are disabled and intercell spacing is `[0,0]`.
So if enabling table grid lines, then either use non-opqaue cell renderers or set intercell spacing to `[1,1]`.
