### ISSUE TITLE
Invoking JFileChooser with FlatLaF crashes VM

### ISSUE THREAD

**Issue by WLenhard** [JFormDesigner/FlatLaf#403]
With the latests Adoptium Release (jdk-17+35), installing FlatLaF and invoking a JFileChooser leads to fatal crash of the VM. It did not happen with jdk-16 and I am not sure, if this is a problem with FlatLaF or Adoptium. OS: Win10 Enterprise 19042.1288

Minimal reproducible example:

```

import javax.swing.JFileChooser;
import javax.swing.SwingUtilities;
import com.formdev.flatlaf.FlatLightLaf;

public class FileChooserTest {
public static void main(String[] args) {
	
	FlatLightLaf.setup();
	
	SwingUtilities.invokeLater(new Runnable() {
		@Override
		public void run() {
			try {
				JFileChooser chooser = new JFileChooser();
				chooser.showSaveDialog(null);
				String file = chooser.getSelectedFile().getName();
				System.out.println(file);
			} catch (Exception e) {
				e.printStackTrace();
			}

		}
	});
}
}

```

**Comment by WLenhard** [comment]
Hi Charly,
I checked with the new JRE17.0.1+12 and can now trace back the error a little bit better. The error still occurs, but only in the x86 runtime and not in x64 on Windows. The runtime crashes when opening a JFileChooser. Other Swing components seem to work fine.

Best regards!

**Comment by DevCharly** [comment]
Can reproduce it.
It is not related to FlatLaf.
Occurs also in Windows L&F.
Metal L&F works because it does not show system icons.

It is a bug in OpenJDK when accessing system icons for the file chooser.
Occurs also in Windows L&F. Metal L&F does not show system icons.

There was a change in this area in JDK 17 to access "large Windows icons", which may be responsible for this crash.
See: https://bugs.openjdk.java.net/browse/JDK-8182043

Maybe this change was never tested on 32 Bit because Oracle distributes only 64 Bit JDKs?

**Comment by DevCharly** [comment]
To avoid the crash I've implemented an workaround, which simply does not use Windows system icons on 32bit Java 17...

64-bit Java 17 is not affected.

**Comment by DevCharly** [comment]
Workaround is in [1.6.2](https://github.com/JFormDesigner/FlatLaf/releases/tag/1.6.2).

**Comment by DevCharly** [comment]
related JDK bug: https://bugs.openjdk.java.net/browse/JDK-8277299

Fixed in Java 18 EA 32bit

I've updated the FlatLaf workaround to show Windows system icons again in Java 18+ 32bit.
So only Java 17 32bit does not show Windows system icons in file chooser tree/table.
