### ISSUE TITLE
JIDE Calendar Chooser

### ISSUE THREAD

**Issue by howudodat** [JFormDesigner/FlatLaf#404]
This is also a component from the paid version.  I have spoken with JIDE and they are ok with creating the UI as long as I contribute it back to them.  I also want to make sure it fits / plays nicely here.

I have created FlatExComboBoxUI, it does 2 things:
1: fixes the border / drawing of the ComboBox
2: adds the ability to have a different icon for the dropdown. 

I know the property names aren't right (I just used TEXT_FIELD_TRAILING_ICON), but it's just a first cut to see whether or not it's worth posting it back.  I'm glad to do so.  I dont really know how to do a PR, would need some hand holding there.

Previous Broken UI  couple of different styles shown  (see weird borders):
![Screenshot from 2021-10-25 07-53-12](https://user-images.githubusercontent.com/3333605/139118809-8d779d41-0179-41f2-a43b-e877387b858e.png)
![Screenshot from 2021-10-25 07-14-49](https://user-images.githubusercontent.com/3333605/139118811-4257c924-1062-4787-8bc4-81d090d88ab3.png)

New UI:
![Screenshot from 2021-10-27 10-39-28](https://user-images.githubusercontent.com/3333605/139118852-c78e80f5-3a3b-421b-a101-80b3ecd0920c.png)

**Comment by DevCharly** [comment]
Sorry, but in this project we can host only open-source code, which depends on open-source libraries.
I assume that your class `FlatExComboBoxUI` depends on classes from the commercial JIDE libraries.
Probably it implements interface [ExComboBoxUI](https://www.jidesoft.com/javadoc/com/jidesoft/plaf/ExComboBoxUI.html).

Since the commercial JIDE libraries are not freely available, we could not compile (and test) code that depends on that libraries.

You can simply keep the code in your project/company.
Or contribute it to the JIDE company.
