### ISSUE TITLE
Opaque JButton with a null background color is transparent

### ISSUE THREAD

**Issue by ebourg** [JFormDesigner/FlatLaf#410]
I've noticed that an opaque JButton with a null background color is transparent. This is different from the Metal look and feel where the button is painted with the default background in this case.

**Comment by DevCharly** [comment]
> ...JButton with a null background color is transparent...

It looks transparent, but it is not.
It is painted using the **background color of the parent**. See [Component.getBackground()](https://github.com/openjdk/jdk/blob/e5cb84e9a1bca321f22d6e3ce13a6026342b4b85/src/java.desktop/share/classes/java/awt/Component.java#L1855-L1862).

Metal is different because it paints a gradient if the background color is a `UIResource`.
If you set button background to `null`, it uses parent background, which is usually a `UIResource` and the button paints the gradient...

If you do following, then Metal fills the button in parent color:
~~~java
button.setBackground( null );
button.getParent().setBackground( Color.red );
~~~

So, this is normal behavior.
