### ISSUE TITLE
JMenu submenu offset above parent

### ISSUE THREAD

**Issue by smileatom** [JFormDesigner/FlatLaf#42]
![Screen Shot 2020-01-13 at 7 15 46 PM](https://user-images.githubusercontent.com/22084334/72311379-5082b300-3639-11ea-927a-e6788795a858.png)
Is this offset of a submenu normal?  This is in a JPopupMenu on macos.
![Screen Shot 2020-01-13 at 8 11 06 AM](https://user-images.githubusercontent.com/22084334/72271988-be4cc180-35dc-11ea-81a3-01fa153c9989.png)

I was expecting the submenu to be top aligned with its parent but its a few pixels higher.  If there were cascading submenus this would keep going higher and higher I would think.  Can this offset be removed?

I see theres not much custom code in the L&F menu UI so I guess maybe theres nothing to be done here.

**Comment by smileatom** [comment]
OK I think I see what the problem is, 
![Screen Shot 2020-01-14 at 12 18 50 AM](https://user-images.githubusercontent.com/22084334/72326152-79b83900-3663-11ea-8102-9a33d0ccaab5.png)

The top (and bottom) margins of the parent JMenu appear to be perhaps a little cut off and the submenu Y coordinate is likely displaying at the Y coordinate of the parent but the parents not drawing those pixels for some reason.  I was going to report that on MacOS the bottom and top of Menus appears to be cutoff (not same height as the rest of items, so this seems to be a side effect of that.

**Comment by smileatom** [comment]
Setting Insets for Menu fixes this offset in a popupmenu

def["PopupMenu.borderInsets"] = Insets(4,0,4,0)
![Screen Shot 2020-01-14 at 8 37 31 PM](https://user-images.githubusercontent.com/22084334/72405463-de2fd280-370d-11ea-8f58-0cc5b54a9c0e.png)

**Comment by smileatom** [comment]
If thats acceptable and not an indicator of another border/inset issue with the default this can be closed.

**Comment by smileatom** [comment]
![Screen Shot 2020-01-14 at 8 40 00 PM](https://user-images.githubusercontent.com/22084334/72405573-44b4f080-370e-11ea-82e6-331aa766d4fa.png)
Actually if you look at the separator and border there appear to be artifacts exposed in the menu or unfinished border drawing.

**Comment by DevCharly** [comment]
> If I set left and right insets equal to top and bottom the artifacts go away so I guess the border drawing expects there to be some left and right insets

Yes, there should be at least 1px at each side.

Unfortunately changing `PopupMenu.borderInsets` affects all popup menus including `JCompoBox`.

Better use following as workaround until it is fixed in FlatLaf:
~~~java
UIManager.put( "Menu.submenuPopupOffsetY", -1 ); 
~~~

BTW I see this issue only on macOS. On Windows it is fine.

> Also is there a UI default to change the menu expansion icon?

You can either change the "arrow type" to "triangle" (see https://www.formdev.com/flatlaf/customizing/#arrow_type) or use the "Flat Darcula" or "Flat IntelliJ" themes.

**Comment by smileatom** [comment]
In .25 I see with default borders the alignment is fixed.  If I use a custom inset though its off from the submenu to parent.  I dont know why but these menus do feel cramped at the top and bottom as if they are cut off on Mac OS by default.  Anyway as a default with no custom insets the bug is fixed.

![Screen Shot 2020-01-17 at 8 56 37 PM](https://user-images.githubusercontent.com/22084334/72658883-146a8d80-396c-11ea-96f9-a98a4faf8c0f.png)

Just wanted to pass along that if you do use custom insets from UI defaults it does push off the submenu alignment even though they have the same insets.

**Comment by DevCharly** [comment]
Yes, I also don't like the current look, but had not the time to improve it for 0.25 because NetBeans 11.3 merge window closes tomorrow and I wanted 0.25 to be in NetBeans.

I'll improve this for 0.26 with 4-6px gap at top/bottom and 0-2px gap at left/right.

I also consider to give the popup menus a slightly different color so that it is easier to distinguish from the underlying window (currently the popup background color is the same as the window/dialog background color).

**Comment by DevCharly** [comment]
The improvement for the menus are now implemented in master branch.

![image](https://user-images.githubusercontent.com/5604048/72762096-a37edc00-3bde-11ea-8677-dc634b714317.png)
![image](https://user-images.githubusercontent.com/5604048/72762198-0a9c9080-3bdf-11ea-86db-2ac8eb45dfed.png)


See change log for list of changes:
https://github.com/JFormDesigner/FlatLaf/blob/master/CHANGELOG.md

Hope you like it 😄

**Comment by smileatom** [comment]
Hey that looks good!

**Comment by DevCharly** [comment]
fixed in 0.26
