### ISSUE TITLE
Password Reveal Button Not Disabled with Password Field

### ISSUE THREAD

**Issue by PicoMitchell** [JFormDesigner/FlatLaf#452]
At first I only noticed that the password reveal button stayed white when the password field was disabled:
<img width="209" alt="Screen Shot 2021-12-20 at 4 55 36 PM" src="https://user-images.githubusercontent.com/7358089/146852835-9c7c992b-5e2b-4351-867d-4b217e455b9d.png">

But, then I realized the password reveal button was actually still enabled and functional when the password field was disabled:
<img width="208" alt="Screen Shot 2021-12-20 at 4 55 43 PM" src="https://user-images.githubusercontent.com/7358089/146852839-3d01cb52-20e6-4654-8c18-a2da7ffa8014.png">

I'm not sure if this is by design or not, since I don't actually thinks it's objectively wrong for the password reveal button to be functional when the password field itself is disabled. But, it visually looks a bit weird when the field is disabled and it may not be desirable behavior in all cases for the password reveal button to still be functional when a password field is disabled.

**Comment by DevCharly** [comment]
There is IMO no need to disable the reveal button if the password field is disabled, isn't it?

The painting is fixed in main branch:
- the reveal button background is no longer filled if not selected
- the hover/pressed/selected button background colors are now translucent, which works nice even if the background color of the password field is changed. E.g.:

![image](https://user-images.githubusercontent.com/5604048/147743864-52b288e7-0b0f-4dd9-bbf7-171b2b092d59.png)
