### ISSUE TITLE
Backward incompatible change for setting the background color of the unified title bar in 2.0-rc1 

### ISSUE THREAD

**Issue by ingokegel** [JFormDesigner/FlatLaf#455]
In FlatLaf 1.x, calling `window.setBackground(...)` set the background for the title bar if the unified background option was set.

In FlatLaf 2.0-rc1,  this has no effect and you have to call `window.getRootPane().setBackground(...)`.

**Comment by DevCharly** [comment]
Didn't know that `window.setBackground(...)` has this side effect...

The "official" way to change title bar background and foreground colors are
using client properties `JRootPane.titleBarBackground` and `JRootPane.titleBarForeground`.
See https://www.formdev.com/flatlaf/client-properties/#JRootPane

~~~java
frame.getRootPane().putClientProperty( "JRootPane.titleBarBackground", Color.red );
~~~

The reason for the changed behavior is commit d6b9e2df62cdce04dda2db07ef2c1551689ae3cd, which sets default colors on root pane.

Have not changed it for final 2.0 because using `window.setBackground(...)` has some drawbacks. 
When a window is first shown, it is filled using the window background color before its content is painted.
Also when resizing the window, new areas are first filled with the window background color before the content layout is updated and painted. If you set window background color to red, its easy to see this effect. This depends on the complexity of the content.

**Comment by ingokegel** [comment]
>The "official" way to change title bar background and foreground colors are
>using client properties JRootPane.titleBarBackground and JRootPane.titleBarForeground.

OK, I did not know that, thanks for clarifying!
