### ISSUE TITLE
Cursor cannot be set in TEXT_FIELD_TRAILING_COMPONENT

### ISSUE THREAD

**Issue by Richard-Tang** [JFormDesigner/FlatLaf#461]
I want to set the Cursor property of JLabel，But the configuration `FlatClientProperties.TEXT_FIELD_TRAILING_COMPONENT` jlabel it will not take cursor effect。

* version
  * java8
  * flatlaf-2.0-rc1

```java
public class Application {

    static {
        FlatLightLaf.setup();
    }

    public static void main(String[] args) {
        SwingUtilities.invokeLater(() -> {
            JLabel jLabel = new JLabel(new FlatTreeLeafIcon());
            JLabel jLabel2 = new JLabel(new FlatTreeLeafIcon());

            jLabel.setCursor(new Cursor(Cursor.HAND_CURSOR));
            jLabel2.setCursor(new Cursor(Cursor.HAND_CURSOR));

            JTextField jTextField = new JTextField();
            jTextField.putClientProperty(FlatClientProperties.TEXT_FIELD_TRAILING_COMPONENT, jLabel2);

            JPanel jPanel = new JPanel();
            jPanel.add(jLabel);
            jPanel.add(jTextField);

            JFrame jFrame = new JFrame();
            jFrame.setTitle("test");
            jFrame.setContentPane(jPanel);
            jFrame.setSize(500, 500);
            jFrame.setVisible(true);
        });
    }
}
```

↓Separate JLabel

![image](https://user-images.githubusercontent.com/30547741/148347579-867df5c7-641d-4820-a4dc-60c51d3671a8.png)

↓In the JTextField Jlabel

![image](https://user-images.githubusercontent.com/30547741/148347547-f1cb0d99-1eff-402a-b151-7e2e0645b7df.png)

cursor not effect

**Comment by DevCharly** [comment]
That's because FlatLaf changes the cursor of leading/trailing components to the default arrow cursor. Otherwise the "text" cursor would be shown on buttons (instead of the default arrow cursor).

To workaround this in FlatLaf 2.0-rc1, simply invoke `setCursor()` after `putClientProperty()`.

Anyway, I've improved FlatLaf behavior in commit a1395a5490dc44862f8d3f142f89b7577dc90764:
the cursor is set only on buttons and toolbars and only if not yet set.

I've also updated the javadoc of the client property `JTextField.leadingComponent`:
https://www.formdev.com/flatlaf/client-properties/#JTextField
