### ISSUE TITLE
Double-click on icon closes window doesn't seem to be through calls `com.formdev.flatlaf.ui.FlatTitlePane.Handler#mouseClicked` ?

### ISSUE THREAD

**Issue by 823984418** [JFormDesigner/FlatLaf#470]
Double-click on icon closes window doesn't seem to be through calls `com.formdev.flatlaf.ui.FlatTitlePane.Handler#mouseClicked` ?
The breakpoint did not hit the method, `TimedWindowEvent`(id=WINDOW_CLOSING) is directly constructed.

```
<init>:48, TimedWindowEvent (sun.awt)
eventLoop:-1, WToolkit (sun.awt.windows)
run:305, WToolkit (sun.awt.windows)
run:834, Thread (java.lang)
```

**Comment by DevCharly** [comment]
That's true. That code is no longer used since the introduction of the native window decorations where this is handled by Windows.

It is used if FlatLaf native window decorations are disabled and custom decorations are enabled (not recommended):
~~~java
System.setProperty( "flatlaf.useWindowDecorations", "false" );
JFrame.setDefaultLookAndFeelDecorated( true );
~~~
