### ISSUE TITLE
Title Bar Title Doesn't Update During Loop Triggered From Non-Modal Child Dialog

### ISSUE THREAD

**Issue by Windchild292** [JFormDesigner/FlatLaf#473]
The expected behaviour is for the client dialog title to update when in a loop, as seen below (e.g. Metal theme).

https://user-images.githubusercontent.com/39067288/151036247-df68f37c-c011-4733-bf9e-33e3b55ca380.mp4

However, this is not the case when using a default FlatLaf theme (e.g. Flat Dark).

https://user-images.githubusercontent.com/39067288/151036216-27a5923d-2a7c-4e3d-b688-de4a8975ff47.mp4

Internally, we use JFrame::setTitle to update the title, and I've validated and ensured that this is being called properly during the date advancement loop.

Finally, it originates in either FlatLaf 1.1 or FlatLaf 1.1.1.

**Comment by DevCharly** [comment]
The problem is that FlatLaf uses Swing components to paint the title bar,
but the AWT thread is blocked by your loop and the title bar is not repainted.
Metal L&F uses a native Windows border that it painted in by Windows in another thread.

I can reproduce it with following, which counts up nicely with Metal L&F, but shows only the last value with FlatLaf:
~~~java
assert EventQueue.isDispatchThread();
for( int i = 0; i <= 100; i++ ) {
    window.setTitle( String.valueOf( i ) );
    Thread.sleep( 10 );
}
~~~

Can't do much here in FlatLaf...

You could run your loop in a background thread and update window title with:
~~~java
SwingUtilities.invokeLater( () -> {
    window.setTitle( newTitle );
} );
~~~

Or leave as is. I mean, nobody can read the title when it changes so fast...

**Comment by Windchild292** [comment]
Thanks for the response and explanation. Closing it as resolved.

Also... those videos were just examples using a test campaign on a rather powerful computer. It can be a lot slower and thus is useful when running a campaign hundreds of times the size or on a weak computer.
