### ISSUE TITLE
On Windows if I set Table.alternateRowColor it messes up list view if I use JFileChooser

### ISSUE THREAD

**Issue by ijabz** [JFormDesigner/FlatLaf#512]
Please see screenshot, setting this value for use in JTable would not expect to affect JFIleChooser

![jfilechooser-windows](https://user-images.githubusercontent.com/1144731/162808365-7a8b1c76-b20b-4934-bc2d-3f5308ed5919.jpg)

**Comment by DevCharly** [comment]
> setting this value for use in JTable would not expect to affect JFIleChooser

But file chooser uses a `JTable` for details view...

This is actually a bug in Swing.
It also occurs in Metal and Windows L&F.
In Nimbus L&F it works because full row selection for file details view is enabled in this L&F.

To fix the issue in FlatLaf, I've also enabed full row selection for file chooser.
