### ISSUE TITLE
scale to 3x causes some components to look inconsistent

### ISSUE THREAD

**Issue by medmedin2014** [JFormDesigner/FlatLaf#521]
If I set `System.setProperty( "flatlaf.uiScale", "3" )` then some components like split pane arrows (both shape and distance between them) and panel line border become inconsistent.

```
FlatLaF: 2.1
OpenJDK Runtime Environment: 17.0.3
Operating System: Manjaro Linux
KDE Plasma Version: 5.24.4
KDE Frameworks Version: 5.92.0
Qt Version: 5.15.3
Kernel Version: 5.17.1-3-MANJARO (64-bit)
Graphics Platform: X11
```

![text2809-7](https://user-images.githubusercontent.com/7027319/164814698-0c45eef8-6c31-467c-a0f3-14d81c4cde12.png)

**Comment by DevCharly** [comment]
Divider arrows look perfect to me (3x, 2x, 1x):
![image](https://user-images.githubusercontent.com/5604048/164889102-7b1af31f-0375-4075-bcf5-e96aa1aa8a56.png)

Seems that you've set the divider width of your splitpane to a fixed/unscaled value.

Titled border also looks good here (at 3x):
![image](https://user-images.githubusercontent.com/5604048/164889335-f3fd601c-dbe4-48ff-97cc-83e5057545ac.png)

Since the title in your screenshot is bold, I assume that you're using a custom/modified titled border that does not scale the insets. Use `FlatLineBorder` for the line border of `TitledBorder`, which scales insets and line thickness.

**Comment by medmedin2014** [comment]
Thanks for your detailed response, after disabling some customized properties I found that the cause of split pane arrows shown as truncated is the property `UIManager.put( "SplitPane.oneTouchButtonSize", 10 )` which doesn't scale like others.
And the border problem was due to using `UIManager.put("TitledBorder.border", new FlatLineBorder(new Insets(0,0,0,0), accentColor))` and after using `new Insets(1,1,1,1)` the problem was fixed.

**Comment by DevCharly** [comment]
FlatLaf can not scale `SplitPane.oneTouchButtonSize` automatically because it is used in `javax.swing.plaf.basic.BasicSplitPaneDivider` in a private variable.
To workaround this, the default value in `FlatLaf.properties`is prefixed with `{scaledInteger}`, which creates an active value and scales the number on access.

https://github.com/JFormDesigner/FlatLaf/blob/bcdc0a8fce5c637ea1336ff5da6b0c578b948a38/flatlaf-core/src/main/resources/com/formdev/flatlaf/FlatLaf.properties#L641

You can achieve the same in Java code with:
~~~java
UIManager.put( "SplitPane.oneTouchButtonSize", (javax.swing.UIDefaults.ActiveValue) t -> UIScale.scale( 10 ) );
~~~

**Comment by medmedin2014** [comment]
Thanks your help is really precious :+1:
