### ISSUE TITLE
HiDPIUtils.scale can return a rectangle with zero dimensions

### ISSUE THREAD

**Issue by kirill-grouchnikov** [JFormDesigner/FlatLaf#557]
There's a bit of a setup to this, more specifically, to have a certain combination of rotation and translation (maybe just rotation) installed on the graphics context. I use that in Radiance to rotate the visuals of tabs in LEFT and RIGHT placement.

If you have these inputs to the scale method:
```
transform = AffineTransform[[-0.0, 2.5, 820.0], [-2.5, 0.0, 557.5]]
x = 0
y = 0
width = 54
height = 19
```

The rectangle returned is `java.awt.geom.Rectangle2D$Double[x=820.25,y=557.25,w=0.0,h=0.0]`

Notice it has zero width and height

**Comment by kirill-grouchnikov** [comment]
I think I can apply the "anti" rotation before calling `HiDPIUtils.paintAtScale1x` and then apply the rotation again inside on my side. Not sure if this is worth tracking in FlatLaf if you don't use it in any rotation scenarios.

**Comment by DevCharly** [comment]
The result is correct because the `scaleX` and `scaleY` fields of the `AffineTransform` are `0.0`,
which results in zero width/height 😉

**Comment by kirill-grouchnikov** [comment]
This matrix is a result of a rotation + a translation. No scaling involved, so I don't think that the expected result is an empty rectangle. I have a workaround on my side so I'm not blocked.

**Comment by DevCharly** [comment]
Indeed, rotating by 90 or 270 degrees changes `scaleX` and `scaleY` to zero. That's surprising...

~~~java
AffineTransform tt = new AffineTransform();
System.out.println( tt );
tt.translate( 100, 200 );
System.out.println( tt );
tt.rotate( Math.toRadians( 270 ) );
System.out.println( tt );
System.out.println( tt.getScaleX() );
System.out.println( tt.getScaleY() );
~~~

outputs

~~~
AffineTransform[[1.0, 0.0, 0.0], [0.0, 1.0, 0.0]]
AffineTransform[[1.0, 0.0, 100.0], [0.0, 1.0, 200.0]]
AffineTransform[[-0.0, 1.0, 100.0], [-1.0, 0.0, 200.0]]
-0.0
0.0
~~~

**Comment by DevCharly** [comment]
> I don't think you can deconstruct an arbitrary transform into its "original" parts, as you can have multiple chained transforms of all three types.

That's true, but actually only the current state is needed.

> Maybe you can apply the matrix on all four (or just three) corners of the rectangle to determine the scaled width and height. Apply on (0, 0) and (width, 0), and the distance between the two points is the scaled width. Then on (0, 0) and (0, height) and the distance is the scaled height.

Thanks for this idea. I have considered it, but since I thought that this would work only for 0, 90, 180 and 270 degree rotations (even though it is unlikely that other rotations are used), I started to googling....

It is "simple" mathematics:
https://math.stackexchange.com/questions/13150/extracting-rotation-scale-values-from-2d-transformation-matrix#answer-13165

Following works for me:

~~~java
double scaleX = Math.hypot( t.getScaleX(), t.getShearX() );
double scaleY = Math.hypot( t.getScaleY(), t.getShearY() );
if( t.getScaleX() < 0 )
    scaleX = -scaleX;
if( t.getScaleY() < 0 )
    scaleY = -scaleY;

double rotation = Math.atan2( t.getShearY(), t.getScaleY() );
double rotationDegrees = Math.toDegrees( rotation );
~~~

I'll try to integrate this into `HiDPIUtils`...

**Comment by DevCharly** [comment]
This is now fixed in main branch. Rotation is now handled correctly.

There is also a small app that I used to test whether `g.fillRect(...)` and
`HiDPIUtils.paintAtScale1x( (...) -> g.fillRect(...) )` produce the same result.

![image](https://user-images.githubusercontent.com/5604048/176905554-4e082b66-3c74-46c0-b58c-1e5a48ead6b4.png)

Red rectangle is filled without `HiDPIUtils` and green rectangle is filled using `HiDPIUtils`.

**Comment by eirikbakke** [comment]
Impressive math! I remember bumping into the same problem when printing in Landscape mode with the Java Printing API. My quick solution was to just rotate the transform 90 degrees until I could get the scaling the old way. But this is better, and handles non-orthogonal rotations.

For the scalings 1x, 1.5x, and 2x and 90 degree transform, does this calculation yield exact integer scalings?

**Comment by eirikbakke** [comment]
@DevCharly Yes! Fair enough for the non-90-degree scalings.
