### ISSUE TITLE
Button rounded border

### ISSUE THREAD

**Issue by Bodyash** [JFormDesigner/FlatLaf#559]
When using Button.arc + Button.bordercolor + Button.borderWidth everything is okay
![image](https://user-images.githubusercontent.com/2454569/174825216-8c3887b0-89f1-44c8-be00-a5ab3f916dea.png)

But if I use just Button.border the background shape is square and button.arc is ignored. But button look like oval.

![image](https://user-images.githubusercontent.com/2454569/174825690-61b54a1a-4e06-4aee-a15b-8363394ed9a2.png)

**Comment by DevCharly** [comment]
This is because in the first case, class `FlatButtonBorder` (extends `FlatBorder`) is used.
The button knows that this border supports rounded corners and fills its background using corner radius from the border.

In second case, class `FlatLineBorder` is used, which is not designed to be used as component/button border. This border does not support focus indication (which you do not need in your design) or different border colors for hover, disabled and focused.
The button does not know that this border has rounded corners...

I'll have a look whether it makes sense to change this...
