### ISSUE TITLE
Tool bar buttons with tab style leave traces on High DPI

### ISSUE THREAD

**Issue by Chrriis** [JFormDesigner/FlatLaf#582]
Hi,

While making sure our application works properly on Windows with 125% scale factor, I found a new bug related to tool bar buttons with tab style.

Here is a screenshot:
![ToolBarButtonsHighDpi](https://user-images.githubusercontent.com/1174202/186256610-2249d292-e70a-4b03-97c7-1c1c62dd8513.png)

Button2 is selected and Button1 is hovered. Button5 and Button3 left some traces from previous selections, which is not correct.
Note that when the tooltip disappears, some repainting occurs that might clear some of the traces. I got the gray trace after showing the tooltip and changing selections.

Here is the test case:
[ToolBarButtonTestOnHighDpi.zip](https://github.com/JFormDesigner/FlatLaf/files/9410389/ToolBarButtonTestOnHighDpi.zip)
The button at the bottom allows to increase the top gap, because this problem only happens for certain "y" locations.

It took me hours to isolate that one in a standalone test case! Do not hesitate if you need more information 😉

**Comment by DevCharly** [comment]
Many thanks for the test case 👍 

Looks like a rounding issue in Swing, caused by painting only a small region when e.g. painting button hover.

There are two cases:

1. painting whole window: the full height of the button is filled
2. re-painting only the button: not the full height of the button is filled

![image](https://user-images.githubusercontent.com/5604048/186274482-aa0ac16b-aaa8-4fdb-addf-04380ce5a2a3.png)

In both cases, the same simple fill operation is used: `g.fillRect( 0, 0, c.getWidth(), c.getHeight() );`

Don't yet know what makes the difference... 😕

**Comment by Chrriis** [comment]
Possibly related JDK bugs:
https://bugs.openjdk.org/browse/JDK-8253530
https://bugs.openjdk.org/browse/JDK-8272707

**Comment by Chrriis** [comment]
And the bug I opened: https://bugs.openjdk.org/browse/JDK-8292976

**Comment by DevCharly** [comment]
see PR #864
