### ISSUE TITLE
FlatLaf altering AWT components on MacOS

### ISSUE THREAD

**Issue by tferr** [JFormDesigner/FlatLaf#583]
On MacOS 12.4, AdoptOpenJdk 1.8.0_202, application with both Swing and AWT components[1]:
While Swing components work fine, AWT components get modified once FlatLaf is loaded. See snapshot below of a AWT Dialog that has only AWT components (no Swing) before loading FlatLaf (left) and after (right). Notice how round edges are missing. Also buttons and drop-down choice can no longer be highlighted when using tab-navigation, which makes it harder to know which button is active (in the snapshot the 'OK' button is highlighted).

Is there a way to avoid this?

![Montage](https://user-images.githubusercontent.com/2439948/187936914-29f92ece-bd98-4983-bdb8-9d74984d13ba.png)

[1] an ecosystem of plugins, some using AWT, others Swing, JavaFx: https://github.com/fiji/fiji

**Comment by DevCharly** [comment]
The reason that AWT components look different when using FlatLaf
is that AWT components use Swing components internally on macOS.
If no look and feel is set, then `AquaLookAndFeel` is used for AWT.

Unfortunately there were some issues in FlatLaf that cause the missing focus indicator and the wrong round corners.
Also button and choice component background needs special handling for AWT.
Hover effect on checkbox was also broken.

Those issues are fixed in latest `2.5-SNAPSHOT`: https://github.com/JFormDesigner/FlatLaf#snapshots

**Comment by DevCharly** [comment]
Implemented some improvements/fixes in latest commits:

- use light theme for AWT components if dark FlatLaf theme is active (AWT is always light)
- made AWT peer background compatible with Aqua Laf
- ScrollBar: disable hover because scroll bar does not receive mouse exited event

When using **FlatLaf Dark**, AWT components previously looked like this:

![image](https://user-images.githubusercontent.com/5604048/189494419-6eb28dce-1343-416a-bebb-e295f51b91d1.png)

Now AWT components always use light FlatLaf theme (even if the Swing dialogs use dark theme):

![image](https://user-images.githubusercontent.com/5604048/189494458-e0aca632-f7b0-4218-82a7-41e3140528fb.png)

**Comment by tferr** [comment]
Thanks a lot. Just tested the 2.5 SNAPSHOT, and everything looks great!
