### ISSUE TITLE
How does UI scale work?

### ISSUE THREAD

**Issue by rkeen-siemens** [JFormDesigner/FlatLaf#590]
I understand that the default font sizes vary based on platform as described on the [Typography page](https://www.formdev.com/flatlaf/typography/). However, it seems that setting the default font also affects the UI scale factor. Setting the default font to 10 (`defaultFont = 10`) results in no scaling. Not setting it results in no scaling on Windows, but 1.5 scaling on Linux (CentOS 7.9 with Gnome 3) even though Gnome has no scaling set either in the displays settings panel or the font panel in Tweaks.

My application (built upon the NetBeans 15 platform) has a number of raster images that don't scale with the UI scale setting although other elements around them do. Is there a way to either have everything scale (including raster elements) or prevent anything from scaling? I'm using Java 17 if it makes a difference as I know there were changes in Java 9+ in this area.

If we cannot scale uniformly, I'd like to force no scaling (at least until we convert our legacy assets to scale). I've tried overriding the values in my theme's properties file with the following but it doesn't seem to have any effect.

```
flatlaf.uiScale = 1
flatlaf.uiScale.enabled = false
```

Although setting the default font to 10 does result in no scaling on both Windows and Linux, it doesn't seem like the right way to prevent scaling. I can then change the font via the NetBeans `--fontsize` argument to a more reasonable size and FlatLaf remains unscaled, but if there's a better way I'd love to know.

**Comment by DevCharly** [comment]
On Linux the system font and the display DPI are used to compute default font size for Swing/AWT. This is done in class [LinuxFontPolicy](https://github.com/JFormDesigner/FlatLaf/blob/main/flatlaf-core/src/main/java/com/formdev/flatlaf/LinuxFontPolicy.java). Then the font size is divided by `15` to compute the FlatLaf user scale factor. See [UIScale](https://github.com/JFormDesigner/FlatLaf/blob/596ff3382dc068c3765ffe91c99cad8b31d12f4c/flatlaf-core/src/main/java/com/formdev/flatlaf/util/UIScale.java#L261).

So if your display has a larger DPI, then the AWT font size may be something like 22, which would result in a scale factor 1.5.

On Windows with Java 17 the situation is different because here Java scales everything and FlatLaf user scale factor is usually `1.0`.

Ideally, the visual size of text in FlatLaf apps should be (nearly) the same as in system apps.
If this is the case then it is probably better not to disable FlatLaf scaling.
Otherwise text may be too small and hard to read.

>  Is there a way to either have everything scale (including raster elements)...

Not automatically.
For FlatLaf it is hard to know which raster elements (icons) needs scaling and which not.
Maybe it could scale icons of labels and buttons.
But nothing can be done in FlatLaf if custom components are used for painting.

BTW there is a class [ScaledImageIcon](https://github.com/JFormDesigner/FlatLaf/blob/main/flatlaf-core/src/main/java/com/formdev/flatlaf/util/ScaledImageIcon.java) in FlatLaf that makes it easier to scale-up image icons (`javax.swing.ImageIcon`).

> or prevent anything from scaling?

Yes. Set **system property** `flatlaf.uiScale.enabled` to `false`.
See https://www.formdev.com/flatlaf/system-properties/

**Comment by rkeen-siemens** [comment]
Setting the system property `flatlaf.uiScale.enabled` to `false` works. Thanks for pointing out my misreading of the documentation there.

Once we update our raster resources, I'll need to revisit the scaling, but I was seeing a font size of 21 on Linux with a scale factor of 1.5 so that matches your expectation.
