### ISSUE TITLE
Inconsistent behaviour of JDialog.setGlassPane on Windows x64 to other architectures (AArch64) and other OS

### ISSUE THREAD

**Issue by derreisende77** [JFormDesigner/FlatLaf#630]
I am using code where at a certain time setGlassPane() is called for a JDialog.
On **Windows 11 x64** the result looks as follows (no titlebar visible):
![win11_x64](https://user-images.githubusercontent.com/8466092/208984301-f23f717a-5e3d-4afd-b9de-82a9cd3394a1.png)

This is different to macOS and Linux, where titlebar remains visible:
![macOS_aarch64](https://user-images.githubusercontent.com/8466092/208984412-74e06333-9182-4d69-a041-6acf85f59212.jpg)
![linux_amd64](https://user-images.githubusercontent.com/8466092/208984447-15acb56b-c4bd-4cce-b0ae-084d623a9e81.png)

And interestingly, running the same code on **Windows 11 Arm64** results in this (titlebar remains visible):
![win11_aarch64](https://user-images.githubusercontent.com/8466092/208984558-d2af1840-5a9d-40f5-8bd3-95e41ca7b077.jpg)

The behaviour on windows is inconsistent to other platforms and it is inconsistent for the same OS on different architectures.

**Comment by derreisende77** [comment]
Forogot to mention screenshots were made with FlatLaf 3.0

**Comment by mac-dl** [comment]
hey, What is the component of the icon in loading?

**Comment by derreisende77** [comment]
@mac-dl `JXBusyLabel` with flatlaf-swingx

**Comment by DevCharly** [comment]
Thanks for reporting.

The reason for the different behavior on various platforms is that only Windows 10/11 x86/x64 use FlatLaf custom window decorations by default, which means that the window title bar is implemented in Swing and the glass pane overlaps the title bar.

Anyway, I've changed the behavior so that the glass pane no longer overlaps the title bar.

Fixed in latest 3.1-SNAPSHOT: https://github.com/JFormDesigner/FlatLaf#snapshots
