### ISSUE TITLE
Icons do not scale when scaling UI under Linux using GNOME desktop environment

### ISSUE THREAD

**Issue by adriankiess** [JFormDesigner/FlatLaf#688]
Dear Maintainer,

I recently implemented the BaseMultiResolutionImage ( https://docs.oracle.com/en/java/javase/17/docs/api//java.desktop/java/awt/image/BaseMultiResolutionImage.html ) into my Java Swing applications, so that the icons can scale when scaling the UI. I tested this under Windows 10, where it works great with the standard Java look and feels and the FlatLaf look and feels.

Now testing this under Debian Linux with the GNOME desktop environment, the standard look and feels do not scale, but the FlatLaf look and feels do scale (great!) – but the icons do not.

So in fact, under Debian Linux with GNOME desktop environment with FlatLaf look and feels, where I tested the scaling of icons, the icons do not scale — but the UI does.

I attached a screenshot below:

![juliaset-screenshot-flatlaf-linux-gnome-ui-scales-but-icons-do-not](https://github.com/JFormDesigner/FlatLaf/assets/102819800/c0d91cbe-7a15-4b48-8b8c-40b3473804da)

Maybe there is way to also let the icons scale with the UI under Linux.

Thank you very much in advance.

Sincerely,

Adrian Kieß

**Comment by DevCharly** [comment]
It works on Windows because Java (v9 and later) do some scaling and then use multi-resolution images for painting.

But on Linux, Java usually does not scale.
FlatLaf does UI scaling itself (if necessary), but not for images.

If you have a custom implementation of `javax.swing.Icon`, you could use `com.formdev.flatlaf.util.UIScale.scale(int)` in `getIconWidth()` and `getIconHeight()` to scale icon width and height.

Additionally you need to handle scaling in `paintIcon()`. I think following should work (not tested):

~~~java
public void paintIcon( Component c, Graphics g, int x, int y ) {
    Graphics2D g2 = (Graphics2D) g.create();
    try {
        g2.translate( x, y );
        UIScale.scaleGraphics( g2 );
        super.paintIcon( c, g2, 0, 0 );
    } finally {
        g2.dispose();
    }
}
~~~

As alternative, you could use FlatLaf class `com.formdev.flatlaf.util.ScaledImageIcon` instead of class `ImageIcon`.
It uses multi-resolution images for painting.

https://github.com/JFormDesigner/FlatLaf/blob/main/flatlaf-core/src/main/java/com/formdev/flatlaf/util/ScaledImageIcon.java

**Comment by adriankiess** [comment]
Dear Karl,

thank you very much for your kind explanation.

The ideal thing then, most probably then, would be, that Java supports UI and Icon scaling under Linux too — now that the GNOME desktop environment is capable of UI scaling.

Thank you all again for this great look and feel package.

Sincerely and with greetings from Leipzig, Germany,

Adrian Kieß

**Comment by DevCharly** [comment]
> The ideal thing then, most probably then, would be, that Java supports UI and Icon scaling under Linux too — now that the GNOME desktop environment is capable of UI scaling.

Well, it actually does support scaling, but Java does not automatically pick up system scale factor.
However you could either use Java system property `sun.java2d.uiScale` or environment variable `GDK_SCALE` to scale Java applications on Linux. See https://wiki.archlinux.org/title/HiDPI#AWT/Swing

**Comment by adriankiess** [comment]
The icon scaling works very well with -Dsun.java2d.uiScale=2 under Debian Linux. Thank you a lot!

Adrian Kieß
