### ISSUE TITLE
flicker on tab title in dark mode

### ISSUE THREAD

**Issue by grandinj** [JFormDesigner/FlatLaf#690]
Hard to describe, but here goes:

When my app is fairly quiet:

(*) If I mouse-over the tab title in a JTabbedPane, sometimes (about 5% of the time) the title will flicker and sometimes, it will settle into a not-selected state even though the mouse is over it. Moving the mouse a little will fix it.

When my app is very busy

(*) If I mouse-over the tab title, it flickers constantly at a fairly high rate.

Some kind of invalidation or temporary-focus issue maybe?

If you could point me to the area of code that handles this, I could maybe add some breakpoints and see what hits.

Thanks a lot for an awesome library!

**Comment by DevCharly** [comment]
> If you could point me to the area of code that handles this, I could maybe add some breakpoints and see what hits.

Well, the painting is done in `FlatTabbedPaneUI.paintTab()`, but a breakpoint there probably does not help because Swing paints "asynchron" via repaint manager. So you can't see the source of the repaint request... Setting a breakpoint at `JComponent.(long tm, int x, int y, int width, int height)` could show the source, but I doubt that this is invoked very often...

Maybe it has something to do with some popup (e.g. a tooltip)?
Try a breakpoint at `FlatPopupFactory.getPopup()`.
