### ISSUE TITLE
Placeholder alignment

### ISSUE THREAD

**Issue by pablotecheraa** [JFormDesigner/FlatLaf#721]
The `JTextField` component supports the client property __"JTextField.placeholderText"__, which takes as default alignment __"ComponentOrientation.LEFT_TO_RIGHT"__. I propose that if you set a different alignment for the text using __"setHorizontalAlignment(SwingConstants.CENTER)"__ the "placeholder" text should be aligned in that direction as well.

Since the placeholder text uses "ComponentOrientation" it is not possible to align it to the center when using "setHorizontalAlignment".

![1](https://github.com/JFormDesigner/FlatLaf/assets/85675526/eef68de6-b2f1-4063-a0fc-c279f609eca2)
![2](https://github.com/JFormDesigner/FlatLaf/assets/85675526/298ab1cc-3c38-4324-81b4-79270b1fdaf2)
![3](https://github.com/JFormDesigner/FlatLaf/assets/85675526/40b52d52-da30-473f-8d4d-b9f50dba3667)

When "setHorizontalAlignment.CENTER" is not defined use "LEFT_TO_RIGHT" or "RIGHT_TO_LEFT".

**Comment by DevCharly** [comment]
Thanks for reporting. 👍 

fixed in latest `3.3-SNAPSHOT`: https://github.com/JFormDesigner/FlatLaf#snapshots

Placeholder now respects horizontal alignment property:

![grafik](https://github.com/JFormDesigner/FlatLaf/assets/5604048/5022810a-6d7e-4c83-9e04-13f75b0abd78)

And for right-to-left component orientation:

![grafik](https://github.com/JFormDesigner/FlatLaf/assets/5604048/0982349c-0658-4a3e-9cb3-7f2519c0f7f1)

**Comment by DevCharly** [comment]
fixed in FlatLaf 3.2.1
