### ISSUE TITLE
Unable to upgrade to any versions after 1.6.5

### ISSUE THREAD

**Issue by SakthiRJ** [JFormDesigner/FlatLaf#724]
I have been utilizing version 1.6.5 of FlatLaf, and I recently attempted to update to the newest release, version 3.0. However, I also experimented with earlier releases, and unfortunately, I encountered the following error message. Versions 1.6.5 and earlier function properly without any issues. I've conducted thorough checks, including verifying connectivity and reviewing my application, and everything appears to be in order.

~~~
java.net.SocketException: Connection reset
	at java.base/java.net.SocketInputStream.read(SocketInputStream.java:186)
	at java.base/java.net.SocketInputStream.read(SocketInputStream.java:140)
	at java.base/java.net.SocketInputStream.read(SocketInputStream.java:200)
	at util.csLaunchHandler3.run(csLaunchHandler3.java:189)
Connection Error : /10.64.1.50, 47463, Connection reset
Unable to communicate with the server, possible network problem.
~~~

**Comment by DevCharly** [comment]
FlatLaf does not contain any networking code and the stack does not have any relation to FlatLaf (or Swing).

Hard to tell why your application is not working with newer FlatLaf versions, but because FlatLaf works in other applications, it is probably a problem in your application. 😉 

BTW the newest version is 3.2
