### ISSUE TITLE
JTextField background not set correctly

### ISSUE THREAD

**Issue by alemberg2020** [JFormDesigner/FlatLaf#732]
Since I upgraded from 1.6.5 to 2.0 the background of textfields is not set, when the editibility via "setEditable" is changed. In my opinion is the reason a wrong condition in com.formdev.flatlaf.ui.FlatTextFieldUI.updateBackground(JTextComponent, Color, Color, Color, Color, Color). Please replace:

```
if( oldBackground != background &&
			oldBackground != disabledBackground &&
			oldBackground != inactiveBackground &&
			oldBackground != oldDisabledBackground &&
			oldBackground != oldInactiveBackground )
		  return;
```

with:

```
if( !Objects.equals(oldBackground, background) &&
			!Objects.equals(oldBackground, disabledBackground) &&
			!Objects.equals(oldBackground, inactiveBackground) &&
			!Objects.equals(oldBackground, oldDisabledBackground) &&
			!Objects.equals(oldBackground, oldInactiveBackground) )
		  return;
```
because these fields are objects and a comparison based on identity makes no sense. In my case the background of JTextFields is always white whether is editable or not.

![grafik](https://github.com/JFormDesigner/FlatLaf/assets/70012846/15a25086-74ab-4593-b585-33b413f2ea62)

Screenshot (left FlatLaf > 1.6.5, right FlatLaf 1.6.5)
![grafik](https://github.com/JFormDesigner/FlatLaf/assets/70012846/f3c61282-0ad6-4dc0-8d30-9196a4ecbc88)

**Comment by alemberg2020** [comment]
In addition, here are the values of the variables for better understanding:
![grafik](https://github.com/JFormDesigner/FlatLaf/assets/70012846/f18a62f5-d1c3-4ad2-9214-1e23e292cead)

**Comment by alemberg2020** [comment]
After I changed locally the class with the changed condition, the background will be updated.

**Comment by DevCharly** [comment]
Hmm, here this works correctly 😕 

Do you invoke `setBackground()` somewhere on these components?
Maybe something like `myTextField.setBackground( UIManager.getColor( "Panel.background" ) )`?
Then remove it 😉 

> ... because these fields are objects and a comparison based on identity makes no sense.

That's not true. It makes sense in this case.
It ensures that the background is updated only if current background is one the "known" colors of that UI delegate.
As soon as you change the background from to outside, this logic is disabled.

This is same logic as in `BasicTextUI.updateBackground()` which is used for Java Core L&Fs.
See https://github.com/openjdk/jdk/blob/3481a485716a1949706a4dcb94181b07e88e804d/src/java.desktop/share/classes/javax/swing/plaf/basic/BasicTextUI.java#L270-L272

E.g. if value of UI property `TextField.background` is `#fff` and you invoke `myTextField.setBackground( Color.white )`.
When using reference comparison, then the text field stays white even if calling `myTextField.setEnabled( false )` or `myTextField.setEditable( false )`. This is the expected behavior.
But when using `equals()`, as you suggest, the textfield would change its background when disabled or not-editable.

**Comment by DevCharly** [comment]
@alemberg2020 have you checked you code whether you invoke `setBackground()` on the text fields?
