### ISSUE TITLE
JTree root node renderring problems

### ISSUE THREAD

**Issue by TheEntropyShard** [JFormDesigner/FlatLaf#747]
Root node of a JTree is rendered too high or so with FlatLaf.

FlatLaf:
![flatlaf](https://github.com/JFormDesigner/FlatLaf/assets/109285316/9a834e96-37f0-4d32-8b9e-3730f696a4b2)

Java default:
![java](https://github.com/JFormDesigner/FlatLaf/assets/109285316/e73648ac-eaab-4678-b6ee-e4c548ed2a2d)

Windows 10 Laf:
![image](https://github.com/JFormDesigner/FlatLaf/assets/109285316/316f6d92-3ef8-4c2e-91d0-eed1ddadc93c)

So, you see the problem. How this can be fixed?

To be more specific, I am using FlatLaf like this:
```java
JDialog.setDefaultLookAndFeelDecorated(true);
JFrame.setDefaultLookAndFeelDecorated(true);
FlatIntelliJLaf.setup();
```
and I also wrap JTree in a JScrollPane.

**Comment by DevCharly** [comment]
That's because your root node not does not have any text.
Give it an useful text, or at least one space character, and it works.

Metal and Windows L&F do not have this problem because they use icons, which are also considered to compute preferred height of rows. FlatLaf hides node icons by default, which results in too small row height if text is also empty.

Or show node icons:

~~~java
UIManager.put( "Tree.showDefaultIcons", true );
~~~

**Comment by TheEntropyShard** [comment]
Oh, that's why. Thanks for the quick response!
