### ISSUE TITLE
Extraction issues with native libraries on macOS and Linux

### ISSUE THREAD

**Issue by AndyAtTV** [JFormDesigner/FlatLaf#797]
On Windows everything works as expected: The appropriate library is extracted to 'java.io.tmpdir'/flatlaf.temp, and when I use flatlaf.nativeLibraryPath it is picked up from there (or extracted if I deliberately use the wrong path)

On macOS and Linux nothing works as expected and both O/S "fail" in the same way: If I use flatlaf.nativeLibraryPath="." (or any relative path) and whether or not I manually put the native lib there then the flatlaf error message says it can't find the library (using the wrong name!) and says it will extract it. For example on Linux it says "Did not find external library ./libflatlaf-linux-x86_64.so, using extracted library instead". On macOS a similar message appears, again with 'lib' prepended to the library name.

If I then put the library in the correct place and rename it with 'lib' added to the name (e.g. libflatlaf-linux-x86_64.so) then no error message appears and it appears to work okay. So it seems that the code is pre-pending a spurious 'lib' to the library name.

If I use flatlaf.nativeLibraryPath="system" then it doesn't seem to matter if I put the native lib on any of the 'system' paths, or not, it always fails. I always get a flatlaf error message saying e.g. "Did not find external library flatlaf-linux-x86_64.so, using extracted library instead". Note that in this case the 'lib' is not prepended to the library name in the message, but it never seems to pick up the native library no matter where I place it.

Finally, with both Linux and macOS and with all the configurations I've tried, when the error message says it is extracting it (and when I don't use flatlaf.nativeLibraryPath), I've not yet been able to find an extracted library in the entire filesystem, and especially not within java.io.tmpdir. So it doesn't seems to be extracting the library when it fails to find it.

For the Linux/macOS tests I'm using a x64 laptop running the latest Mint, and an Apple M macmini running the latest macOS v14. I'm using the latest Adoptium Java 17 on both systems, and FlatLaf 3.3, and I've repeated every test on each O/S in Eclipse, standalone apps using jars, and standalone apps after using jlink.

**Comment by DevCharly** [comment]
First of all: FlatLaf automatically extracts native libraries from flatlaf.jar to temporary folders. 
There is **no need** to set system property `flatlaf.nativeLibraryPath` for this use case.

If you like to ship the FlatLaf native libraries with your application (to avoid loading from temporary folder),
it is highly recommended to grab them from Maven central.
See https://www.formdev.com/flatlaf/native-libraries/
In this case, it is also **not necessary** to set `flatlaf.nativeLibraryPath`.

> On Windows everything works as expected: The appropriate library is extracted to 'java.io.tmpdir'/flatlaf.temp, and when I use flatlaf.nativeLibraryPath it is picked up from there (or extracted if I deliberately use the wrong path)

Extracting to `'java.io.tmpdir'/flatlaf.temp` is the default behavior on Windows.
Setting system property `flatlaf.nativeLibraryPath` for this case is **not necessary**!

> On macOS and Linux nothing works as expected and both O/S "fail" in the same way: If I use flatlaf.nativeLibraryPath="." (or any relative path) and whether or not I manually put the native lib there then the flatlaf error message says it can't find the library (using the wrong name!) and says it will extract it. For example on Linux it says "Did not find external library ./libflatlaf-linux-x86_64.so, using extracted library instead". On macOS a similar message appears, again with 'lib' prepended to the library name.

The expected file names for the native libraries are the same as used in flatlaf.jar:
https://github.com/JFormDesigner/FlatLaf/tree/main/flatlaf-core/src/main/resources/com/formdev/flatlaf/natives

They start with `lib` on macOS and Linux.

Relative paths are relative to the working directory of your application.
Are you sure that you started your application in the right directory?
In Eclipse launch config dialog you can specify the working directory on "Arguments" tab.

> If I then put the library in the correct place and rename it with 'lib' added to the name (e.g. libflatlaf-linux-x86_64.so) then no error message appears and it appears to work okay. So it seems that the code is pre-pending a spurious 'lib' to the library name.

Yes, this is usual library naming on macOS and Linux.

> If I use flatlaf.nativeLibraryPath="system" then it doesn't seem to matter if I put the native lib on any of the 'system' paths, or not, it always fails. I always get a flatlaf error message saying e.g. "Did not find external library flatlaf-linux-x86_64.so, using extracted library instead". Note that in this case the 'lib' is not prepended to the library name in the message, but it never seems to pick up the native library no matter where I place it.

To be correct it says: `Did not find library flatlaf-linux-x86_64 in ...` (without `.so`)
So the leading `lib` and the trailing `.so` or `.dylib` are indeed missing in that error message.

For flatlaf.nativeLibraryPath="system", FlatLaf uses method `System.loadLibrary(libName)`, which expects libraryname without leading `lib` and trailing `.so` or `.dylib`.

If you think that flatlaf.nativeLibraryPath="system" does not work, then you've either put the FlatLaf natives to the wrong directory, or they have wrong names, or there is a bug in Java.
FlatLaf only invokes `System.loadLibrary("flatlaf-linux-x86_64")` in that case.

> Finally, with both Linux and macOS and with all the configurations I've tried, when the error message says it is extracting it (and when I don't use flatlaf.nativeLibraryPath), I've not yet been able to find an extracted library in the entire filesystem, and especially not within java.io.tmpdir. So it doesn't seems to be extracting the library when it fails to find it.

Yes, this is because they are immediately deleted after loading.

The source code of FlatLaf is freely available. You can simply debug into following method to find out whether or where it is extracted:
https://github.com/JFormDesigner/FlatLaf/blob/eed11d211b6aec915c44a261a65bc8b021a08fe8/flatlaf-core/src/main/java/com/formdev/flatlaf/util/NativeLibrary.java#L102-L154

For me it works fine.

**Comment by DevCharly** [comment]
Thanks for your feedback. I've fixed/improved the log messages and the system property docs:
https://github.com/JFormDesigner/FlatLaf/blob/722dde63df58e144bff8933de6c662fe8c1e08e4/flatlaf-core/src/main/java/com/formdev/flatlaf/FlatSystemProperties.java#L174-L205

> FYI My confusion about the linux/macos library filenames arose because the files in Maven (where I manually downloaded them from) don't have lib in front of them, ...

Yes, the Maven native file names do not work with `flatlaf.nativeLibraryPath` in FlatLaf 3.3 without renaming.
You need to remove the version and add `lib`.
In FlatLaf 3.4, they will work.

> ... and there is no reference to the lib prefix [in the documentation](https://www.formdev.com/flatlaf/native-libraries/).

But there is also no reference to the system property `flatlaf.nativeLibraryPath` on that page 😉 

Is there a reason that you want use `flatlaf.nativeLibraryPath`?
