### ISSUE TITLE
Keyboard shortcut F2 on JTable cell does not work on macOS

### ISSUE THREAD

**Issue by pejax** [JFormDesigner/FlatLaf#810]
I updated to FlatLaf 3.4 and checked the extended functionality using F2 to select and edit a JTable cell. It works in Fedora 39/JDK21 but not on macOS 14.3.1/JDK21. On macOS the cell goes into edit mode with the cursor positioned after the text (just like CMD-L) but the text is not selected. It is a very useful feature, though, because text selection and immediately overwriting the old content is cool.

**Comment by DevCharly** [comment]
This does not work because there are no key bindings for F2 for JTable (and JTree) on macOS.
(because this would be unusual on macOS; in Finder the Enter key can be used to start cell editing)

What you see is the standard behavior of JTable when pressing any key: start editing and append pressed character to end of text.
Since F2 does not represent any character, nothing is appended.
The same happens if you press F3, F4, ...
