### ISSUE TITLE
TabPane scrollButtonsPolicy

### ISSUE THREAD

**Issue by CRY-D** [JFormDesigner/FlatLaf#815]
The forward/backward scroll arrow buttons never display when I switch to RTL orientation.

`Flatlaf demo LTR`

![Screenshot_20240303_004009](https://github.com/JFormDesigner/FlatLaf/assets/16564491/b630e20d-f50a-4b63-b8b4-11616af2f682)

`**Flatlaf demo RTL** does not show`

![Screenshot_20240303_004210](https://github.com/JFormDesigner/FlatLaf/assets/16564491/2f336864-a63c-4dd8-9af0-4f47baf71115)

`**mine RTL** does not show`

![Screenshot_20240303_004305](https://github.com/JFormDesigner/FlatLaf/assets/16564491/0fdbfea4-128a-434e-b3ec-bcc5a7cd3fd8)

**Comment by DevCharly** [comment]
Scroll buttons are not supported for right-to-left and top/bottom tab placement.
This is a known limitation.

I tried to implement it, but unfortunately, it is not possible because of bugs in Java class `BasicTabbedPaneUI.ScrollableTabSupport`. 😢 

https://github.com/JFormDesigner/FlatLaf/blob/d26819d2684d21ea7b00c29a0e28e2e9a6799476/flatlaf-core/src/main/java/com/formdev/flatlaf/ui/FlatTabbedPaneUI.java#L3770-L3788

**Comment by DevCharly** [comment]
Forgot to mention that you can use mouse wheel to scroll tabs.
Move the mouse pointer to the tab area and rotate mouse wheel.
This is usually easier and faster than using scroll buttons.
