### ISSUE TITLE
TitleBar color

### ISSUE THREAD

**Issue by koldou** [JFormDesigner/FlatLaf#82]
Depending on these selected ColorSchme, set the JFrame TitleBar colour, the default background color.

**Comment by DevCharly** [comment]
Yes, that would be great, but I don't think that it is possible to change TitleBar color in pure Java because it comes from the operating system.

A solution would be to re-implement the whole window title in Java (issue #47).
Then we have full control, but probably loose OS specific behavior and look.

**Comment by DevCharly** [comment]
this is now released in [FlatLaf 0.37](https://github.com/JFormDesigner/FlatLaf/releases/tag/0.37)
