### ISSUE TITLE
JToggleButton border

### ISSUE THREAD

**Issue by lgoix** [JFormDesigner/FlatLaf#86]
I'm using the Material Darker Contrast Theme, with 2 JToggleButton side-by-side, it is hard to see which one is currently selected

![image](https://user-images.githubusercontent.com/16083263/79754934-4500f100-82e6-11ea-8696-a78d8e0f8cce.png)

Can I set a border that is the color of the selected background ?

When I specify the buttons to be a "tab", the unselected button has no background, it is hard to see it exists. But it is easy to see which one is selected.

`button.putClientProperty( "JButton.buttonType", "tab" );`

![image](https://user-images.githubusercontent.com/16083263/79754614-cdcb5d00-82e5-11ea-866b-31c7a7043410.png)

Can we add a border to the JButton of type = tab ?

**Comment by DevCharly** [comment]
@lgoix because IntelliJ IDEA does not use plain toggle buttons, theme authors usually do not specify or test them.

So I've fixed them in FlatLaf 0.32.

New Material Darker Contrast toggle buttons:

![image](https://user-images.githubusercontent.com/5604048/80126558-91248d80-8593-11ea-80e2-9c50a80ac79d.png)


There is now also a new [FlatLaf IntelliJ Themes Pack](https://github.com/JFormDesigner/FlatLaf/tree/master/flatlaf-intellij-themes) that bundles all themes that the FlatLaf Demo uses into a JAR and provides Java classes to use them. This also makes it easier to update the theme because it is no longer necessary to download a `.theme.json` file.

If you don't want use the themes pack, please update [Material Darker Contrast.theme.json](https://github.com/JFormDesigner/FlatLaf/blob/master/flatlaf-intellij-themes/src/main/resources/com/formdev/flatlaf/intellijthemes/themes/material-theme-ui-lite/Material%20Darker%20Contrast.theme.json) to latest version because there are some improvements.

**Comment by DevCharly** [comment]
Regarding border on "tab" style toggle buttons:
yes you can replace it. The "underline" is not painted in the default border.

Its probably a good idea to extend `FlatButtonBorder` (for minimum button width) 
or `FlatBorder` (for scaled margins).

**Comment by lgoix** [comment]
This is better, thank you
