### ISSUE TITLE
EditorPane text color under dark theme

### ISSUE THREAD

**Issue by kirill-grouchnikov** [JFormDesigner/FlatLaf#9]
All text controls use light text color under dark theme except for JEditorPane

**Comment by DevCharly** [comment]
Hmm, looks good to me on Windows. What OS and Java version do you use?

**Comment by kirill-grouchnikov** [comment]
Java 13 on macOS Mojave

**Comment by kirill-grouchnikov** [comment]
Maybe this is only for HTML content:

```java
        JEditorPane jep1 = new JEditorPane("text/html;", "Sample <b>content</b><br> <u>text</u>");
```

**Comment by DevCharly** [comment]
Yes, text color (and the font) for HTML content is wrong.

Many thanks for reporting.

**Comment by JFormDesigner** [comment]
thanks, fixed in 0.14

**Comment by DevCharly** [comment]
@kirill-grouchnikov after fixing this issue I had a look at `SubstanceEditorPaneUI` to see whether you're also using the `JEditorPane.HONOR_DISPLAY_PROPERTIES` client property, which is the case. Anyway, I've noticed that `super.installListeners();` is invoked twice. Don't know whether this is intentional or a mistake...

https://github.com/kirill-grouchnikov/radiance/blob/master/substance/src/main/java/org/pushingpixels/substance/internal/ui/SubstanceEditorPaneUI.java#L131-L132

**Comment by kirill-grouchnikov** [comment]
Thanks for catching that. No reason for double call. Will remove.
