### ISSUE TITLE
HTML is displayed faulty 3.5 / 3.5.2

### ISSUE THREAD

**Issue by frankb33** [JFormDesigner/FlatLaf#905]
Hi Charly, 
first: I appreciate your amazing job!
I just stumbled about an issue. If I put HTML text  in a JLable with 3.5 or 3.5.2 it seems to ignore some styling. In 3.4.1 and the older releases (3.2, 3.1, 3.0) I used it worked as expected.
I have tested the issue right now on Linux Mint XFCE 22, Adoptium Java 21 and MacOS ARM 14.7 Java 21.

I attached  the HTML (appending as code seems to have issues here)
[example_html.txt](https://github.com/user-attachments/files/17618202/example_html.txt)

looks now like that :
![Label_with_3_5](https://github.com/user-attachments/assets/120f1ee8-71af-41b5-8298-10a4f6dd8835)

  and before it was ok:
![Label_with_3_4_1](https://github.com/user-attachments/assets/e91efa8a-56c5-40c7-b535-b65fb1815e69)

All the best
Frank

**Comment by DevCharly** [comment]
Thanks for reporting.

This is because FlatLaf does not recognize the `<style type='text/css'>` tag and inserts `<head>...</head>` before the styles, which makes the HTML invalid and the table styles become part of the body text.

fixed in latest `3.5.3-SNAPSHOT`: https://github.com/JFormDesigner/FlatLaf#snapshots

**Comment by frankb33** [comment]
Thanks a lot! Stunned by your service!!
