### ISSUE TITLE
JComboBox: opaque option ignored

### ISSUE THREAD

**Issue by VISTALL** [JFormDesigner/FlatLaf#928]
Hello. Setting `opaque=false` ignored by painter of combobox

Code
```java
public class ComboTest {
    public static void main(String[] args) {
        SwingUtilities.invokeLater(() -> {
            FlatIntelliJLaf.setup();

            JFrame frame = new JFrame();
            frame.setSize(500, 500);
            frame.setLocationByPlatform(true);
            frame.setLocationRelativeTo(null);

            JPanel panel = new JPanel();
            panel.setBackground(Color.PINK);
            frame.add(panel);

            JComboBox<Object> box = new JComboBox<>(new Object[]{"Test1", "Test2", "Test3"});
            box.setOpaque(false);
            box.setBorder(new EmptyBorder(0, 0, 0, 0));
            
            panel.add(box);

            frame.setVisible(true);
        });
    }
}
```

| **Actual** | **Expected**|
|-------------------------------------|---------------------------------------------|
|![{1D5861CB-5B50-426B-B6B2-BA4982023AF1}](https://github.com/user-attachments/assets/7bd78029-e715-42bb-80b8-2702a6bbff64)|![{DC65D005-228E-4819-A720-5E0EFB5F5C0E}](https://github.com/user-attachments/assets/d4cd5213-1bc8-4f8f-8df0-2053c80d89d7)|

I think problem in this part

https://github.com/JFormDesigner/FlatLaf/blob/main/flatlaf-core/src/main/java/com/formdev/flatlaf/ui/FlatComboBoxUI.java#L555
```java
boolean paintBackground = true;
```
Must be changed to
```java
boolean paintBackground = c.isOpaque();
```

And cleanup lower `if`

**Comment by DevCharly** [comment]
Sorry, but your expectation is wrong 😉 

This does not work in any Laf.
Try Metal, Nimbus, Windows L&F...
None of them make the combobox transparent.

If FlatLaf many components are non-opaque by default, which is necessary for rounded borders.

`opaque=false` is **not** a general way to make components transparent.
It is a hint to the repaint manager to optimize re-painting.

You (usually) can achieve a transparent component by setting a transparent background color and set opaque to false.

~~~java
comboBox.setBackground( new Color( 0, true ) );
comboBox.setOpaque( false );
~~~

In case of FlatLaf combobox, you also need to set the button background color:

~~~java
comboBox.putClientProperty( FlatClientProperties.STYLE, "background: #0000; buttonBackground: #0000" );
comboBox.setOpaque( false );
~~~

For editable comboxes, use `buttonEditableBackground` instead of `buttonBackground`.
