### ISSUE TITLE
Menus feel very small

### ISSUE THREAD

**Issue by Chrriis** [JFormDesigner/FlatLaf#96]
Menus feel odd because they look shrunk. I think they should take a bit more visual space to help readability and also because modern UI tend to take more space than old UI.

See this comparison of a Windows look-and-feel menu and FlatLaf:
![SmallMenus](https://user-images.githubusercontent.com/1174202/80969581-1de40c80-8e1a-11ea-928a-b9bdab4971c0.png)

I also find that the selected items are not very visible, maybe a very little bit darker could help.

**Comment by smileatom** [comment]
This should be configurable

**Comment by Chrriis** [comment]
Here is the same screenshot with 2 variations with 1 and 2 pixels around:
![SmallMenus2](https://user-images.githubusercontent.com/1174202/80971213-b24f6e80-8e1c-11ea-83ef-d07bd2fdd0d2.png)

**Comment by smileatom** [comment]
This property is generally called "iconGap" but is some sad inheritance from JLabel that was never really implemented properly.

**Comment by smileatom** [comment]
Also, although perhaps OS correct, the alignment in Windows menu is not particularly, "good"

**Comment by DevCharly** [comment]
Hmm, didn't notice until now that the FlatLaf menus are so much smaller that the Windows LaF menus.  Probably because I work on a HiDPI screen at 150% scaling and most of the time use Java 8 for testing, where FlatLaf scales but WinLaf does not. So menus look similar in Java 8. But running with Java 14 shows the difference clearly.

The margins for menu items are specified in `MenuItem.margin`, `Menu.margin`, `CheckBoxMenuItem.margin` and `RadioButtonMenuItem.margin`. The current value is `2,6,2,6`. Type is `Insets`

Increasing the top and bottom margin by 1px to `3,6,3,6` would make FlatLaf menu items have exact the same height as in Windows 10 Explorer, which is 33px on my display (at 150% scaling). Surprisingly the Eclipse menu items have only 30px and Thunderbird 31px. Strange, thought that native menus would have same height...
IntelliJ IDEA menu items are 31px, FlatLaf 0.33 are 31px, FlatLaf master are 30px.

Don't think that the Java Windows Laf is a reference here because its menus are much larger than native Windows 10 menus. (41px vs 33px at 150%)

The icon selection color should be of course darker.

**Comment by Chrriis** [comment]
I compared the Explorer menus and you are right: my FlatLaf variation with 1px around matches. I also compared my Eclipse menus and on my setup they match my Explorer menus (maybe we are not using the same theme?).

Does it mean you are you going to change the default to have this 1px more around?

> The icon selection color should be of course darker.

Can't wait to have it fixed 🙂

**Comment by DevCharly** [comment]
> Does it mean you are you going to change the default to have this 1px more around?

Yes.

**Comment by DevCharly** [comment]
The changes are now in master branch.

I've also increased the gap between the icon and text (+2px) in increased the icon selection margin (+1,1,1,1) so that has same height as menu item and there is no gap between "underline" and selection:

![image](https://user-images.githubusercontent.com/5604048/81057559-f39f5700-8ecc-11ea-9867-4ce4dc6129da.png)

**Comment by Chrriis** [comment]
The height of the items is much better!

Now, I wonder if it is a good idea to have the selected icon occupy the full height, because they feel stuck:
![SmallMenus3](https://user-images.githubusercontent.com/1174202/81060943-bee2ce00-8ed3-11ea-9383-a3fdd103d7b5.png)

Maybe you should consider an empty space around this selected icon:
![SmallMenus4](https://user-images.githubusercontent.com/1174202/81060994-da4dd900-8ed3-11ea-97cf-6c2acd57755e.png)

**Comment by DevCharly** [comment]
Good point. Changed in master branch.

**Comment by Chrriis** [comment]
It feels better! Thanks!

**Comment by DevCharly** [comment]
just released in 0.34
