### ISSUE TITLE
Combobox.editableBackground / Combobox.background is ignored.

### ISSUE THREAD

**Issue by chris576** [JFormDesigner/FlatLaf#97]
I am trying to make a own IntelliJ Theme. At the moment I am working on ComboBoxes and TextFields. I am trying to define a background for a editable Combobox like this: 
        "ComboBox": {
            "background": "#60b8d0",
            "editableBackground": "#0bbaf6",
            "nonEditableBackground": "#e8ebe4",
            "buttonBackground": "#8e9585"
        },
The tags "background" and "editableBackground" have no effect. Instead the general background, or the background from a TextField is used. I want to define a own background for the TextField within a ComboBox.

**Comment by DevCharly** [comment]
This is currently not possible because of following code:

https://github.com/JFormDesigner/FlatLaf/blob/4bd3b889dc1246086d2b470b1dd7eb924bef96bf/flatlaf-core/src/main/java/com/formdev/flatlaf/IntelliJTheme.java#L164-L165

Value of `ComboBox.editableBackground` is always replaced with value of `TextField.background` because IntelliJ IDEA uses `TextField.background` for editable ComboBox, but FlatLaf uses `ComboBox.editableBackground`. Without this code line, editable ComboBox background would be wrong in many IntelliJ themes because `ComboBox.editableBackground` is not specified in any of the 3rd party IntelliJ themes.

I'll check whether I can change this without breaking themes...

BTW why do you create an IntelliJ theme? Is this for IntelliJ IDEA too?
If not, it would be probably easier to create a FlatLaf theme using a `.properties` file.

All you need is a properties file (e.g. `MyTheme.properties`) and a Java class in same package and with the same basename (e.g. `MyTheme.java`) that extends either `FlatLightLaf` or `FlatDarkLaf`.

**Comment by NerdyChris** [comment]
I do not want to create an look and feel for the IntelliJ IDEA. I try to create a look and feel for our software. Therefore it has to bee 100 % customizable at run time for the user. The flat laf works with .properties or Json. Our configuration service is working with xml. My Approach was to set up a xml configuration. After that I would try to convert it to a syntax that your IntelliJTheme class (as InputStream) understands.

**Comment by chris576** [comment]
I have seen, that I am not able to define a background for JLabels. Is this an IntelliJ problem as well?

**Comment by DevCharly** [comment]
@chris576 in your case I would recommend to avoid Json because there are too many incompatibilities between IntelliJ Json and FlatLaf. Look at class [IntelliJTheme](https://github.com/JFormDesigner/FlatLaf/blob/master/flatlaf-core/src/main/java/com/formdev/flatlaf/IntelliJTheme.java) how many fixes are necessary to make it work.

Better go the direct way. Convert your XML configuration to a `java.util.Properties` object and pass it to the constructor of the new class [FlatPropertiesLaf](https://github.com/JFormDesigner/FlatLaf/blob/master/flatlaf-core/src/main/java/com/formdev/flatlaf/FlatPropertiesLaf.java) (just added to master branch).

If you can't build FlafLaf from master branch, use the latest snapshot: 
https://github.com/JFormDesigner/FlatLaf#snapshots

**Comment by DevCharly** [comment]
> I have seen, that I am not able to define a background for JLabels. Is this an IntelliJ problem as well?

Can't find any restriction for `Label.background`, but labels are non-opaque by default and do not use background color. You have to call `myLabel.setOpaque(true)`.

**Comment by DevCharly** [comment]
Here is an example to use `FlatPropertiesLaf`:

~~~java
Properties properties = new Properties();
properties.put( "@baseTheme", "dark" );
properties.put( "Button.background", "#f00" );
UIManager.setLookAndFeel( new FlatPropertiesLaf( "My theme", properties ) );
~~~

**Comment by chris576** [comment]
Thank you! That helps a lot. 🥇 
After I set up the xml configuration I will try your approach. I will give you feedback on the result.

**Comment by chris576** [comment]
I forgot to set the opaque to true 👍

**Comment by DevCharly** [comment]
The 0.34 release includes the new `FlatPropertiesLaf` class.
